### ISSUE TITLE
Does not work with string values

### ISSUE THREAD

**Issue by dshafik** [staudenmeir/eloquent-json-relations#10]
## Problem

I currently have two models, `Event` and `Account`. `Account` has an `id` column of type string, and `Event` has a `data` column with a JSON value like `{"userId": "12345", "a-bunch-more": "stuff"}`. The query is sending the `Account.id` value as an `integer`, which doesn't match the `string` value in JSON.

## Models

The model classes look like this (some stuff omitted for brevity):

```php
class Account extends Model
{
    use HasJsonRelationships;

   protected $with = ['events'];

  public function events(): HasMany
  {
        return $this->hasMany(Event::class, "data->userId");
  }
}
```

```php
class Event extends Model
{
    use HasJsonRelationships;

    public function account(): BelongsTo
    {
        return $this->belongsTo(Account::class, 'data->userId');
    }
}
```

## Queries

The query being run (per `DB::getQueryLog()`) looks like this:

```sql
select * from "events" where "events"."data"->>'userId' in (?)
```

And the final query for `Student->id = "12345"` looks like:

```sql
select * from "events" where "events"."data"->>'userId' in (12345)
```

Which won't work because `data->>userId` is a string. It needs to be:

```sql
select * from "events" where "events"."data"->>'userId' in ('12345')
```

**Comment by staudenmeir** [comment]
There are two issues:

- The `Account` model requires a [`$keyType`](https://laravel.com/docs/eloquent#eloquent-model-conventions): 

```php
class Account extends Model
{
    protected $keyType = 'string';
}
```

- The `Event` model requires a JSON cast: 

```php
class Event extends Model
{
    protected $casts = [
        'data' => 'json',
    ];
}
```

**Comment by dshafik** [comment]
@staudenmeir that solved it! Thanks! 🙏🏼
