### ISSUE TITLE
Support for custom key

### ISSUE THREAD

**Issue by fcanacmarquis** [staudenmeir/eloquent-json-relations#102]
Hi, thank you for your great work.

Consider:

Profile::class
> user_id
> project_id 
> ...

Photo::class 
>id
>usersId (json of 'user_id's)
>...

How could I get the photos related to a Profiles based on 'user_id' as custom key parameter... something like:

```
class Profile extends Model
{
    use \Staudenmeir\EloquentJsonRelations\HasJsonRelationships;

    public function photos()
    {
       return $this->hasManyJson(Photo::class, 'usersId','user_id');
    }
}

```

I guess, I could use the `hasManyThroughJson` with the User::class,  but I wondered if there was a shortcut using profile->user_id 

Thanks!!!

**Comment by staudenmeir** [comment]
Hi @fcanacmarquis,

> How could I get the photos related to a Profiles based on 'user_id' as custom key parameter... something like:

Did you try that? Is it not working?
