### ISSUE TITLE
hasMany - belongsToJson - hasManyJson 

### ISSUE THREAD

**Issue by fit-vanson** [staudenmeir/eloquent-json-relations#104]
Currently I have:
A-[hasMany]->B-[belongsToJson]->C -[hasManyJson]->D
D-[belongsToJson]-> C-[hasManyJson]->B-[belongsTo]->A
I am having problems to write relationships between A - C, A-D and other relationships between models.
Can someone help me? Thank you very much

**Comment by staudenmeir** [comment]
Hi @fit-vanson,
You can use one of my other packages to define deep relationships like `A` → `C` or `A` → `D`:
https://github.com/staudenmeir/eloquent-has-many-deep#concatenating-existing-relationships

**Comment by fit-vanson** [comment]
Thank you, I tried combining the package you sent me but it seems the result is not what I expected. Can you help me? I want from A to be able to get all of D

**Comment by staudenmeir** [comment]
What are your actual relationships? What deep relationships have you tried? What is the actual vs. expected result?

**Comment by fit-vanson** [comment]
Thank you. i found my solution from package [https://github.com/staudenmeir/eloquent-has-many-deep](https://github.com/staudenmeir/eloquent-has-many-deep#concatenating-existing-relationships)
