### ISSUE TITLE
SqliteGrammar / Sqlite support

### ISSUE THREAD

**Issue by antoniopaisfernandes** [staudenmeir/eloquent-json-relations#108]
Hi,

I'm running the code with Sqlite as the database.

I've managed to have my tests passing by copying `MySqlGrammar` to `SqliteGrammar` and returning false in `supportsMemberOf` method.
![image](https://github.com/staudenmeir/eloquent-json-relations/assets/6171197/ae6bacec-c188-4baf-bc9b-11250f8d9c88)

Do you think we could add Sqlite grammar?

Best

**Comment by staudenmeir** [comment]
Hi @antoniopaisfernandes,
What version of SQLite are you using?

**Comment by antoniopaisfernandes** [comment]
Hi,
I'm using 3.39.2

![image](https://github.com/staudenmeir/eloquent-json-relations/assets/6171197/80a9d219-4cbb-4e26-b576-07b6e1714d3a)

**Comment by staudenmeir** [comment]
How are you using the package in your app? What relationships did you define and test?

**Comment by antoniopaisfernandes** [comment]
I have a Workshop model like this:

```php

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Staudenmeir\EloquentJsonRelations\HasJsonRelationships;
use Staudenmeir\EloquentJsonRelations\Relations\BelongsToJson;

class Workshop extends Model
{
    use HasFactory,
        HasJsonRelationships;

    public $incrementing = false;

    protected $guarded= [];

    protected $casts = [
        'team_leader_ids' => 'json',
    ];

    public function teamLeaders(): BelongsToJson
    {
        return $this->belongsToJson(User::class, 'team_leader_ids');
    }
//...
}
```

And a related model with a scope:

```php
class WorkshopWarranty extends Model
{
    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope(new WorkshopWarrantyScope());
    }

    public function workshop(): BelongsTo
    {
        return $this->belongsTo(Workshop::class);
    }
//...
}


class WorkshopWarrantyScope implements Scope
{
    public function apply(Builder $builder, Model $model): void
    {
        $builder->whereHas('workshop', function (Builder $query) {
            $query->whereHas('teamLeaders', fn (Builder $query) => $query->where('id', auth()->id()));
        });
    }
}
```

Running in MariaDB gets the following SQL:
```sql
SELECT
    *
FROM
    `workshop_warranties`
WHERE
    EXISTS (
        SELECT
            *
        FROM
            `workshops`
        WHERE
            `workshop_warranties`.`workshop_id` = `workshops`.`id`
            AND EXISTS (
                SELECT
                    *
                FROM
                    `users`
                WHERE
                    json_contains(
                        `workshops`.`team_leader_ids`,
                        json_array(`users`.`id`)
                    )
                    AND `id` = 835
                    AND `users`.`deleted_at` IS NULL
            )
    )
```

Running in SQLite
```sql
SELECT
    *
FROM
    "workshop_warranties"
WHERE
    EXISTS (
        SELECT
            *
        FROM
            "workshops"
        WHERE
            "workshop_warranties"."workshop_id" = "workshops"."id"
            AND EXISTS (
                SELECT
                    *
                FROM
                    "users"
                WHERE
                    EXISTS (
                        SELECT
                            1
                        FROM
                            json_each("workshops"."team_leader_ids")
                        WHERE
                            "json_each"."value" IS json_array(`users`.`id`)
                    )
                    AND "id" IS NULL
                    AND "users"."deleted_at" IS NULL
            )
    )
```

Running that SQL in HeidiSQL:
![image](https://github.com/staudenmeir/eloquent-json-relations/assets/6171197/96af3bb2-36aa-43a5-854f-acf1974bda14)


Best

**Comment by staudenmeir** [comment]
Thanks, I'll look into it. SQLite didn't support these relationships when I created the package, but that was five years ago.

**Comment by staudenmeir** [comment]
I've released a new version with SQLite support for relationships like yours.

This update has only been possible since Laravel added support for `whereJsonContains()` on SQLite two weeks ago.
Out of curiosity: Were you waiting for that or was it a coincidence that you startet developing right after the Laravel update?

**Comment by antoniopaisfernandes** [comment]
Wow!! That was fast!

It was a serendipity :)
Developed last week
![image](https://github.com/staudenmeir/eloquent-json-relations/assets/6171197/efb14e1e-123a-4502-88b8-2a16ecedb785)

Your package added 3 months ago:
![image](https://github.com/staudenmeir/eloquent-json-relations/assets/6171197/e8c7a37f-e123-43c0-9dc7-68e20b5fc3a0)


Thank you!

**Comment by ren0v** [comment]
@staudenmeir is there any query performance trick for SQLite as you already have documented for MySQL / PostgreSQL?
https://github.com/staudenmeir/eloquent-json-relations?tab=readme-ov-file#query-performance

**Comment by staudenmeir** [comment]
@ren0v Not that I know of. Are you having performance issues?

**Comment by ren0v** [comment]
Not really. It was just an anticipation to be sure to apply good practices if any :)Le 9 févr. 2024 à 16:07, Jonas Staudenmeir ***@***.***> a écrit :﻿
@ren0v Not that I know of. Are you having performance issues?

**Comment by staudenmeir** [comment]
SQLite is extremely fast, so I don't think performance should be an issue.
