### ISSUE TITLE
laravel compoships

### ISSUE THREAD

**Issue by Xlector** [staudenmeir/eloquent-json-relations#109]
Problem: We cannot use this package with [laravel compoships](https://github.com/topclaudy/compoships)

Error:`Trait method Staudenmeir\\EloquentJsonRelations\\HasJsonRelationships::getAttribute has not been applied as App\\Models\\Model::getAttribute, because of collision with Awobaz\\Compoships\\Compoships::getAttribute`

**Comment by staudenmeir** [comment]
Hi @Xlector,
How are you using or want to use both packages in your model? What relationships did you define or want to define?

**Comment by Xlector** [comment]
hi @staudenmeir , yes I'm using both of the packages 

this using : `HasJsonRelationships` package
`
public function products(){
          return $this->belongsToJson(Product::class,'product_ids');
}
`
this using :`Compoships` package
`
public function warhouses_per_date(){
         return $this->hasMany(Warehouse::class,['date','warehouse_id'],['date','id']);
}
`
using them separately works fine

**Comment by staudenmeir** [comment]
Try combining the packages like this:

```php
class YourModel extends Model
{
    use Compoships, HasJsonRelationships {
        Compoships::getAttribute as getAttributeCompoships;
        HasJsonRelationships::getAttribute as getAttributeJson;
        Compoships::newBelongsTo insteadof HasJsonRelationships;
        Compoships::newHasMany insteadof HasJsonRelationships;
        Compoships::newHasOne insteadof HasJsonRelationships;
    }

    public function getAttribute($key)
    {
        if (is_array($key)) {
            return $this->getAttributeCompoships($key);
        }

        return $this->getAttributeJson($key);
    }
}
```

**Comment by Xlector** [comment]
@staudenmeir thanks , I tried it works great 👌.
