### ISSUE TITLE
use inside function? 

### ISSUE THREAD

**Issue by zavodnyrichard** [staudenmeir/eloquent-json-relations#11]
In database I have only plain JSON array of ids, eg.:
`
[1,5,9]
`

and I need to get the relationship working.

I have a **ProductVariant** model and it _hasMany_ **ProductAttributeOptions** (these are referenced by the ids in that array in ProductVariant; option_ids). How do I get it working? Also how do I use your library scoped to one specific function (variants and options) when defining a relationship? The 'use' directive in function doesn't work for me.

Here is native Laravel relationship represantation of relationships, I need these transfer to your library extension.

```
class ProductAttributeOption extends Model
{
	.
        .
        .

	public function variants() {
		return $this->belongsTo(ProductVariant::class, 'option_ids[]', 'id'); //Here I need reference the id in array
	}
}
```

```
class ProductVariant extends Model
{
	.
        .
        .

	public function options() {
		return $this->hasMany(ProductAttributeOption::class 'id', 'option_ids[]'); //This references the id in array (option_ids) in ProductAttributeOption model option_ids
	}
}
```

Yes, I know vanilla Larevel don't know the [], but this is just for you to better imagine what I want and what the option_ids is (an array). Thank you.

**Comment by staudenmeir** [comment]
You are looking for [many-to-many relationships](https://github.com/staudenmeir/eloquent-json-relations#many-to-many-relationships):

```php
class ProductAttributeOption extends Model
{
    use \Staudenmeir\EloquentJsonRelations\HasJsonRelationships;

    public function variants() {
        return $this->hasManyJson(ProductVariant::class, 'option_ids');
    }
}

class ProductVariant extends Model
{
    use \Staudenmeir\EloquentJsonRelations\HasJsonRelationships;

    protected $casts = [
       'option_ids' => 'json',
    ];

    public function options() {
        return $this->belongsToJson(ProductAttributeOption::class, 'option_ids');
    }
}
```

> How do I get it working? Also how do I use your library scoped to one specific function (variants and options) when defining a relationship?

How do you mean that?

**Comment by zavodnyrichard** [comment]
I can't use the "use" "keyword" inside a function. It returns me an error: 'unexpected use (T_USE).

**Comment by staudenmeir** [comment]
What does your code look like?

**Comment by zavodnyrichard** [comment]
The same as you sent me.

**Comment by staudenmeir** [comment]
Please post the whole class file.
