### ISSUE TITLE
hasOneJson?

### ISSUE THREAD

**Issue by mattkingshott** [staudenmeir/eloquent-json-relations#113]
Hi Jonas,

Amazing work as always!

Just wondered if it would be possible to do a `hasOneJson` instead of `hasManyJson`? Is there maybe a simple way to achieve this by chaining to `hasManyJson`?

Thanks!

**Comment by mattkingshott** [comment]
So based on my experimentation, it would appear that if you override `HasManyJson` and replace `->get()` within the `getResults()` method with `->first()`, it works as expected.

e.g.

```php
class HasOneJson extends HasManyJson
{
    /**
     * Retrieve the results of the relationship.
     *
     */
    public function getResults() : mixed
    {
        return ! is_null($this->getParentKey()) ? $this->first() : $this->related->newCollection();
    }
}
```

If this seems acceptable, it would be great if this could be merged in. Thanks! 🙏

**Comment by staudenmeir** [comment]
Hi @mattkingshott,
I'll look into it. There also need to be some adjustments for eager loading, but it shouldn't be complicated.

**Comment by mattkingshott** [comment]
Awesome!

**Comment by staudenmeir** [comment]
I released a new version with the `HasOneJson` relation:
https://github.com/staudenmeir/eloquent-json-relations?tab=readme-ov-file#hasonejson

**Comment by mattkingshott** [comment]
Great stuff! Thank you 🙏🏻
