### ISSUE TITLE
Relationship for hasMany with array

### ISSUE THREAD

**Issue by gms8994** [staudenmeir/eloquent-json-relations#12]
I have two tables:

people: id, name, team_ids
teams: id, name

Where `people.team_ids` is a JSON array.

I have a relationship on people:

```
public function teams() {
    return $this->hasMany(Team::class, 'id', 'team_ids[]');
}
```

It looks like `HasJsonRelationships` expects the field to be and object with a key-value of arrays (`{ "teams": [ 1, 2, 3 ] }`) whereas our system is `[ 1, 2, 3 ]` in the team_ids field.

From what I can tell, it looks like `getAttributeValue` is missing handling of of this situation. Would it be possible to add said handling? I've done some exploratory digging, and it looks like this is the place to add the code, but I'm not completely certain what would need to be added.

**Comment by gms8994** [comment]
It looks like adding the following to `getAttributeValue` will work, though I'm not sure it covers all the cases?

```
if (Str::endsWith($key, '[]')) {
            if (substr($key, -2) === '[]') {
                $key = substr($key, 0, -2);
            }

            return $this->getAttributeValue($key)[0];
        }
```

**Comment by staudenmeir** [comment]
This is a [many-to-many relationship](https://github.com/staudenmeir/eloquent-json-relations#many-to-many-relationships), please use the `BelongsToJson` type:

```php
public function teams() {
    return $this->belongsToJson(Team::class, 'team_ids');
}
```
