### ISSUE TITLE
integr data

### ISSUE THREAD

**Issue by eslam147** [staudenmeir/eloquent-json-relations#121]
I encountered an issue where I was searching for a teacher's ID in data stored as a JSON string, e.g., ["1","154"]. When I searched using the ID, no data was returned because the ID was an integer. Please help resolve this issue.

**Comment by staudenmeir** [comment]
Hi @eslam147,
Please see issues like https://github.com/staudenmeir/eloquent-json-relations/issues/114#issuecomment-2270025519: You need to convert these strings to integers before storing them in the database.
