### ISSUE TITLE
HasManyThroughJSON

### ISSUE THREAD

**Issue by ianfortier** [staudenmeir/eloquent-json-relations#13]
Hi! First I really like this package! Good job! 👍 

I wonder if it's possible to use a HasManyThroughJSON to query a parent relationship items.

Thanks

**Comment by staudenmeir** [comment]
What do your tables look like?

**Comment by ianfortier** [comment]
Basically;

**Model # 1 : Device Model**
'App\Device\DeviceModel'
id

I need to query all the "Compatible ProductVariant Model # 3 " through the product (Model # 2)

**Model # 2 : Product**
'App\Product\Product'
id
compatible_devices_models_ids <--- JSON

`
public function variants()
    {
        return $this->hasMany('App\Product\ProductVariant', 'product_id');
    }


 public function compatible_device_models()
    {
        return $this->belongsToJson('App\Device\DeviceModel', 'compatible_device_models_ids');
    }
`



**Model # 3 : Product Variant**
'App\Product\ProductVariant'
id
product_id

`
    public function product()
    {
        return $this->belongsTo('App\Product\Product', 'product_id');
    }
`

**Comment by staudenmeir** [comment]
This is not supported at the moment. I'll look into it.

**Comment by staudenmeir** [comment]
I don't think I'll add this relationship type anytime soon. The implementation would be quite complex and I don't see that many use cases.

In the meantime, you can imitate it by combining a `HasManyJson` and a `HasMany` relationship.

**Comment by ianfortier** [comment]
Can you provide an example of a combination of `HasManyJson ` and `HasMany ` for me and other people looking for a similar solution :)?

Feel free to close this issue! Thanks again for the help!

**Comment by staudenmeir** [comment]
Define two separate relationships and combine them with an accessor:

```php
class DeviceModel extends Model
{
    use \Staudenmeir\EloquentJsonRelations\HasJsonRelationships;

    public function products()
    {
        return $this->hasManyJson('App\Product\Product', 'compatible_device_models_ids');
    }

    public function getProductVariantsAttribute()
    {
        $productVariants = $this->products->pluck('variants')->flatten();

        return new \Illuminate\Database\Eloquent\Collection($productVariants);
    }
}

class Product extends Model
{
    use \Staudenmeir\EloquentJsonRelations\HasJsonRelationships;

    protected $casts = [
        'compatible_device_models_ids' => 'json',
    ];

    public function variants()
    {
        return $this->hasMany('App\Product\ProductVariant', 'product_id');
    }
}

Device::find($id)->productVariants;
```

Use eager loading to prevent unnecessary queries:

```php
Device::with('products.variants')->find($id)->productVariants;
```

**Comment by staudenmeir** [comment]
I released a new version that adds support for `HasManyThrough` relationships (Laravel 9+):
https://github.com/staudenmeir/eloquent-json-relations#has-many-through-relationships

```php
class DeviceModel extends Model
{
    use \Staudenmeir\EloquentHasManyDeep\HasRelationships;

    public function productVariants()
    {
        return $this->hasManyThroughJson(
            ProductVariant::class, Product::class, new JsonKey('compatible_device_models_ids'), 'product_id'
        );
    }
}
```
