### ISSUE TITLE
syncWithoutDetaching

### ISSUE THREAD

**Issue by nurieff** [staudenmeir/eloquent-json-relations#15]
Great package!
What about small but useful features **syncWithoutDetaching**?

https://laravel.com/docs/5.8/eloquent-relationships#updating-many-to-many-relationships

**Comment by staudenmeir** [comment]
You can actually use `attach()` for this. Because the relationship doesn't support duplicate pivot keys, `attach()` behaves the same way `syncWithoutDetaching()` would.

**Comment by nurieff** [comment]
Thanks
