### ISSUE TITLE
hasManyJson not prepending prefix on withCount & whereHas?

### ISSUE THREAD

**Issue by debkumar-techpro** [staudenmeir/eloquent-json-relations#17]
The error I am getting is 

> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'skills.id' in 'where clause' (SQL: select `id`, `name`, (select count(*) from `fc_x_details` where json_contains(`fc_x_details`.`skill`, json_object(skill_id, **`skills`**.`id`)) and `fc_x_details`.`deleted_at` is null) as `x_detail_count` from `fc_skills` where `status` = 1 and `fc_skills`.`deleted_at` is null limit 92 offset 0)

The skills in bold should be fc_skills but the prefix is not taking. The code I am using is given below:
```
Skill::select('id', 'name')
            ->where('status', '1')
        ->withCount('xDetail')
```
The relation is:
```
public function xDetail()
    {
        return $this->hasManyJson(XDetail::class, 'skill');
    }
```
The field is fc_x_details.skill is of type json containing array of ids of table fc_skills like the following:
`[1,2,3]`

Please try to reply as soon as possible. I am in the middle of a project and is very much in need of a solution.

**Comment by staudenmeir** [comment]
I've released a new version that fixes this issue.

**Comment by debkumar-techpro** [comment]
Thanks for such quick response. I have updated the package to 1.2.4 and the issue is fixed now.
