### ISSUE TITLE
with() not working for hasOne relation between json to json field!!

### ISSUE THREAD

**Issue by debkumar-techpro** [staudenmeir/eloquent-json-relations#18]
I have a relation as following:
```
class X {
public function eX()
    {
        return $this->hasOne(EX::class, 'file->>e', 'data->field');
    }
}
}
```
I have a field **data** (JSON: '{ "field": "some_value" }') in X and field **file** (JSON: '{ "e": "some_value" }') in EX.

I am calling the relation with the following query:
```
X::select('*')
   ->with('eX')
   ->get();
```

The output of the query I am getting is having a **e_x** key with value null but I have data according to the relation, so I was expecting an object with the child being joined. The output of getQueryLog() is following:

> array:2 [
>   0 => array:3 [
>     "query" => "select `*` from `x` where `x`.`deleted_at` is null
>     "time" => 0.68
>   ]
>   1 => array:3 [
>     "query" => "select * from `e_x` where `e_x`.`file`->>'$."e"' in (?, ?, ?) and `e_x`.`deleted_at` is null"
>     "bindings" => array:3 [
>       0 => "1568851023-7283a7f28d582bcb3ef1ba1f83010fd6"
>       1 => "1568851208-adbde7e3a2ca4613eb83682ffeab00cb"
>       2 => "1568851823-c04d0530718306aedc0080864c1c7599"
>     ]
>     "time" => 0.44
>   ]

I am getting the correct value in **e_x** if the bindings of index 1 is having only one element but when the number of elements is greater than 1 then the output of **e_x** is null

Please help me with a solution. I will be waiting for your reply.

**Comment by staudenmeir** [comment]
`->>` is incorrect, it's `->`:

```php
public function eX()
{
    return $this->hasOne(EX::class, 'file->e', 'data->field');
}
```

**Comment by debkumar-techpro** [comment]
we have tried using -> as well, but no luck. The data was still not coming

**Comment by staudenmeir** [comment]
Do you have JSON casts in both models?

**Comment by debkumar-techpro** [comment]
yes

**Comment by staudenmeir** [comment]
Please post both models.

**Comment by debkumar-techpro** [comment]
```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class X extends Model
{
    use SoftDeletes;
    use \Staudenmeir\EloquentJsonRelations\HasJsonRelationships;

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['deleted_at'];
    protected $casts  = [
        'data'      => 'json',
    ];

    public function eX()
    {
        return $this->hasOne(EX::class, 'file->e', 'data->field');
    }
}
```

```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class EX extends Model
{
    use SoftDeletes;
    use \Staudenmeir\EloquentJsonRelations\HasJsonRelationships;

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden   = ['deleted_at'];
    protected $fillable = ['file'];
    protected $casts    = [
        'file' => 'json',
    ];
}


```

**Comment by staudenmeir** [comment]
> I am getting the correct value in e_x if the bindings of index 1 is having only one element but when the number of elements is greater than 1 then the output of e_x is null

Can you explain that in more detail?

**Comment by staudenmeir** [comment]
Can you provide sample data that lets me reproduce the issue?

**Comment by debkumar-techpro** [comment]
please wait, I will be giving you sample data in a few minutes.

**Comment by debkumar-techpro** [comment]
Here is the sample data as sql.
[xex.zip](https://github.com/staudenmeir/eloquent-json-relations/files/3631983/xex.zip)

**Comment by staudenmeir** [comment]
Which models give you an incorrect result?

**Comment by debkumar-techpro** [comment]
what do you mean? please elaborate

**Comment by staudenmeir** [comment]
How does this sample data not work? Where do I see the incorrect relationship?

**Comment by debkumar-techpro** [comment]
The relation works for the following query:
`X::with('eX')->find(14)`
Output:
> {
>     "x": {
>         "id": 14,
>         "data": {
>             "field": "1568851023-7283a7f28d582bcb3ef1ba1f83010fd6"
>         },
>         "created_at": "2019-09-19 17:27:08",
>         "updated_at": "2019-09-19 17:50:05",
>         "e_x": {
>             "id": 2,
>             "file": {
>                 "e": "1568851023-7283a7f28d582bcb3ef1ba1f83010fd6"
>             },
>             "created_at": null,
>             "updated_at": null
>         }
>     }
> }

but is not working for the following query:
`X::with('eX')->get()`
Output:
> {
>     "xes": [
>         {
>             "id": 3,
>             "data": null,
>             "created_at": "2019-05-20 17:34:59",
>             "updated_at": "2019-05-24 17:58:06",
>             "e_x": null
>         },
>         {
>             "id": 12,
>             "data": null,
>             "created_at": "2019-07-04 20:09:34",
>             "updated_at": "2019-07-04 20:09:34",
>             "e_x": null
>         },
>         {
>             "id": 14,
>             "data": {
>                 "field": "1568851023-7283a7f28d582bcb3ef1ba1f83010fd6"
>             },
>             "created_at": "2019-09-19 17:27:08",
>             "updated_at": "2019-09-19 17:50:05",
>             "e_x": null
>         },
>         {
>             "id": 15,
>             "data": {
>                 "field": "1568851208-adbde7e3a2ca4613eb83682ffeab00cb"
>             },
>             "created_at": "2019-09-19 17:30:10",
>             "updated_at": "2019-09-19 17:35:25",
>             "e_x": null
>         },
>         {
>             "id": 16,
>             "data": {
>                 "field": "1568851823-c04d0530718306aedc0080864c1c7599"
>             },
>             "created_at": "2019-09-19 17:40:33",
>             "updated_at": "2019-09-19 17:40:33",
>             "e_x": null
>         },
>         {
>             "id": 17,
>             "data": {
>                 "field": "1568862172-028e86442ffbcc347e342ac784779d3d"
>             },
>             "created_at": "2019-09-19 20:33:00",
>             "updated_at": "2019-09-19 20:33:00",
>             "e_x": null
>         },
>         {
>             "id": 19,
>             "data": {
>                 "field": null
>             },
>             "created_at": "2019-09-19 20:36:42",
>             "updated_at": "2019-09-19 20:36:42",
>             "e_x": null
>         }
>     ]
> }

**Comment by staudenmeir** [comment]
`X::with('eX')->get()` works for me, I get the correct relationships.

Please create a fresh Laravel installation and see if you can still reproduce the issue without any other packages or customizations.

**Comment by debkumar-techpro** [comment]
What response are you getting with this query `X::with('eX')->get()`?

can you please share the response?

**Comment by staudenmeir** [comment]
```json
[
   {
      "id":3,
      "data":null,
      "created_at":"2019-05-20 12:04:59",
      "updated_at":"2019-05-24 12:28:06",
      "e_x":null
   },
   {
      "id":12,
      "data":null,
      "created_at":"2019-07-04 14:39:34",
      "updated_at":"2019-07-04 14:39:34",
      "e_x":null
   },
   {
      "id":14,
      "data":{
         "field":"1568851023-7283a7f28d582bcb3ef1ba1f83010fd6"
      },
      "created_at":"2019-09-19 11:57:08",
      "updated_at":"2019-09-19 12:20:05",
      "e_x":{
         "id":2,
         "file":{
            "e":"1568851023-7283a7f28d582bcb3ef1ba1f83010fd6"
         },
         "created_at":null,
         "updated_at":null
      }
   },
   {
      "id":15,
      "data":{
         "field":"1568851208-adbde7e3a2ca4613eb83682ffeab00cb"
      },
      "created_at":"2019-09-19 12:00:10",
      "updated_at":"2019-09-19 12:05:25",
      "e_x":null
   },
   {
      "id":16,
      "data":{
         "field":"1568851823-c04d0530718306aedc0080864c1c7599"
      },
      "created_at":"2019-09-19 12:10:33",
      "updated_at":"2019-09-19 12:10:33",
      "e_x":null
   },
   {
      "id":17,
      "data":{
         "field":"1568862172-028e86442ffbcc347e342ac784779d3d"
      },
      "created_at":"2019-09-19 15:03:00",
      "updated_at":"2019-09-19 15:03:00",
      "e_x":{
         "id":3,
         "file":{
            "e":"1568862172-028e86442ffbcc347e342ac784779d3d"
         },
         "created_at":null,
         "updated_at":null
      }
   },
   {
      "id":19,
      "data":{
         "field":null
      },
      "created_at":"2019-09-19 15:06:42",
      "updated_at":"2019-09-19 15:06:42",
      "e_x":null
   }
]
```

**Comment by staudenmeir** [comment]
What does your controller look like?

**Comment by debkumar-techpro** [comment]
can I know what laravel version and mysql version you are working on?

my laravel version is 5.8 and mysql version is 5.7

**Comment by staudenmeir** [comment]
I'm using the same versions.

**Comment by debkumar-techpro** [comment]
Okay, I think I have to find some other way to fix the issue.

But, thanks for your quick responses and appreciate the support.
