### ISSUE TITLE
BelongsTo Relation with array

### ISSUE THREAD

**Issue by LaravelTestGit** [staudenmeir/eloquent-json-relations#19]
Hello,

I'v got table named `received_orders`
and table named `invoices` with column `invoices` (`invoices`.`invoices`)  as JSON
contains received_orders id array
for example

[45,67,154]

the received order with id=45 belongs to this invoice 

I'v tried 

` return $this->BelongsTo('App\Invoice', 'invoices','id');`

` return $this->BelongsTo('App\Invoice', 'invoices[]');`

**Comment by staudenmeir** [comment]
This requires a [many-to-many relationship](https://github.com/staudenmeir/eloquent-json-relations#many-to-many-relationships):

```php
class Invoice extends Model
{
    use \Staudenmeir\EloquentJsonRelations\HasJsonRelationships;

    protected $casts = [
       'invoices' => 'json',
    ];
    
    public function receivedOrders()
    {
        return $this->belongsToJson(ReceivedOrder::class, 'invoices');
    }
}

class ReceivedOrder extends Model
{
    use \Staudenmeir\EloquentJsonRelations\HasJsonRelationships;

    public function invoices()
    {
       return $this->hasManyJson(Invoice::class, 'invoices');
    }
}
```

**Comment by LaravelTestGit** [comment]
Thank You!
