### ISSUE TITLE
Not installing via composer

### ISSUE THREAD

**Issue by Adinathg-94** [staudenmeir/eloquent-json-relations#20]
not installing on composer install. I have added this package through composer require command, it has been installed successfully.But not installing on server via composer install.But downloading on composer update. Here is my composer.json. I only pushed composer.json
`{
"name": "laravel/lumen",
"description": "The Laravel Lumen Framework.",
"keywords": ["framework", "laravel", "lumen"],
"license": "MIT",
"type": "project",
"require": {
    "php": ">=7.1.3",
    "doctrine/dbal": "^2.9",
    "guzzlehttp/guzzle": "^6.3",
    "kreait/firebase-php": "^4.0",
    "laravel/lumen-framework": "5.7.*",
    "lcobucci/jwt": "^3.2",
    "league/flysystem-aws-s3-v3": "~1.0",
     "staudenmeir/eloquent-json-relations": "^1.1",
    "vlucas/phpdotenv": "~2.2"
},
"require-dev": {
    "fzaninotto/faker": "~1.4",
    "phpunit/phpunit": "~7.0",
    "mockery/mockery": "~1.0"
},
"autoload": {
    "classmap": [
        "database/seeds",
        "database/factories"
    ],
    "psr-4": {
        "App\\": "app/"
    }
},
"autoload-dev": {
    "classmap": [
        "tests/"
    ]
},
"scripts": {
    "post-root-package-install": [
        "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
    ]
},
"config": {
    "preferred-install": "dist",
    "sort-packages": true,
    "optimize-autoloader": true
},
"minimum-stability": "dev",
"prefer-stable": true
}`

**Comment by staudenmeir** [comment]
Are you getting an error?
