### ISSUE TITLE
Laravel 6+ suppor?

### ISSUE THREAD

**Issue by paulocr** [staudenmeir/eloquent-json-relations#27]
I see the code was updated 21 days ago so I assume it's active but I am not sure if Laravel 6+ is supported. Can you please confirm? If it is I can perhaps describe an issue I am seeing.

**Comment by staudenmeir** [comment]
Yes, Laravel 6+ is supported.

**Comment by priyankpateltrootech** [comment]
Hi,

I have Laravel 6.16.0, and I'm getting a version error. Could you please confirm, it supports 6.16.0?

An error which I get is as follows:

`Problem 1
    - The requested package laravel/framework (locked at v6.10.1, required as 6.16.0) is satisfiable by laravel/framework[v6.10.1] but these conflict with your requirements or minimum-stability.
  Problem 2
    - don't install illuminate/database 7.x-dev|don't install laravel/framework v6.16.0
    - don't install illuminate/database 7.x-dev|remove laravel/framework v6.16.0
    - staudenmeir/eloquent-json-relations v1.4 requires illuminate/database ^7.0 -> satisfiable by illuminate/database[7.x-dev].
    - Installation request for staudenmeir/eloquent-json-relations ^1.4 -> satisfiable by staudenmeir/eloquent-json-relations[v1.4].
    - Installation request for laravel/framework 6.16.0 -> satisfiable by laravel/framework[v6.16.0].
`

**Comment by staudenmeir** [comment]
@paulocr Please use the installation command from the README:
https://github.com/staudenmeir/eloquent-json-relations#installation

**Comment by paulocr** [comment]
Should the package be auto discovered?

**Comment by staudenmeir** [comment]
No, the package doesn't have any auto-discovery functionality. You need to add the `HasJsonRelationships` trait to your models.

**Comment by paulocr** [comment]
Ok thanks. I did add the trait but wasn't sure about the auto discover part. Thanks

**Comment by staudenmeir** [comment]
Does your relationship work?
