### ISSUE TITLE
hasManyJson(): array_key_exists() expects parameter 2 to be array, null given

### ISSUE THREAD

**Issue by krisnieh** [staudenmeir/eloquent-json-relations#29]
platform: laravel v7.2+ postgresql v12 + eloquent-json-relations v1.4; Follow the guild, exactly.
problem: using json array relations `public function users()
    {
       return $this->hasManyJson('App\User', 'roles[]->role_id');
    }`, the json column:
`[{"role_id":1,"active":true},{"role_id":2,"active":false}]`
when test User::find(1)->roles, return ` array_key_exists() expects parameter 2 to be array, null given`

- If trying to change the Integer 1 to String "1": `[{"role_id":"1","active":true},{"role_id":"2","active":false}]`,
there's no error, but return an empty array.
-trying to use mysql v8.0 instead of postgresql, get the same resaults.

**Comment by staudenmeir** [comment]
Please post both models.

**Comment by krisnieh** [comment]
User.php
```
class User extends Authenticatable
{
    use \Staudenmeir\EloquentJsonRelations\HasJsonRelationships;

    protected $casts = [
       'options' => 'json',
    ];

    public function roles()
    {
        return $this->belongsToJson('App\Role', 'role_ids[]->role_id');
    }
}
```
Role.php
```
class Role extends Model
{
    use \Staudenmeir\EloquentJsonRelations\HasJsonRelationships;

    protected $casts = [
        'options' => 'json',
     ];

    public function users()
    {
       return $this->hasManyJson('App\User', 'role_ids[]->role_id');
    }
}
```
The users table has a json column: role_ids, value(mysql8.0): 
```
[{"active": true, "role_id": 1}, {"active": false, "role_id": 2}]
```
I have tried many times, but not work. Thanks for your help

**Comment by staudenmeir** [comment]
You need to adjust the cast to your JSON column:

```php
class Role extends Model
{
    use \Staudenmeir\EloquentJsonRelations\HasJsonRelationships;

    protected $casts = [
        'role_ids' => 'json',
     ];  ^^^^^^^^

    public function users()
    {
       return $this->hasManyJson('App\User', 'role_ids[]->role_id');
    }
}
```

**Comment by krisnieh** [comment]
I't works, you are always the best!! Thanks for your time!
