### ISSUE TITLE
Strange bug when calling relationship in accessor

### ISSUE THREAD

**Issue by greaterking** [staudenmeir/eloquent-json-relations#3]
Strange but was trying to call a relationship in an accessor like so

```
public function getOptionsAttribute($value) {
        
    //wanted to loop through the actual relation because it carries the additional data needed
    // just a test...to see what is returned
    error_log(print_r( $this->roles->get()->toArray(), true ));

    return json_decode($value, true);
}
```

then if I call the relationship or try to retrieve the options attribute like so... (I used tinker to test)

`\App\User::find(7)->roles` 
or
`\App\User::find(7)->options`

...I get the following

`PHP Notice:  Undefined property: App/User::$roles[]->role_id in /path_to_project/vendor/staudenmeir/eloquent-json-relations/src/Relations/BelongsToJson.php on line 97`

line 97 refers to this line below in the addConstraints() method of BelongsToJson.php 
`$this->query->whereIn($table.'.'.$this->ownerKey, (array) $this->child->{$this->foreignKey});`

Calling other relationships this way, within the accessor,  seem to work except BelongsToJson

**Comment by staudenmeir** [comment]
How is the `roles` relationship defined?

Are you using the latest release `v1.1.1`?

Are you using the `HasJsonRelationships` trait in both the `User` and the `Role` model?

**Comment by greaterking** [comment]
```
public function roles()
{
   return $this->belongsToJson('App\Role', 'options[]->role_id');
}
```

```
public function users()
{
   return $this->hasManyJson('App\User', 'options[]->role_id');
}
```

Using v1.1.1 and yes HasJsonRelationships is in User and Role models

...in fact when I do \App\Role::find(2)->users I get

PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in P/vendor/laravel/framework/src/Illuminate/Support/Arr.php on line 151

The data is stored in Users table like this: [{role_id: 1, other_field: 'xyz'},{role_id: 2, other_field: 'xyz'}]

schema is basically the same as in example: 
```
Schema::create('users', function (Blueprint $table) {
    $table->increments('id');
    $table->json('options');
    $role_id = DB::connection()->getQueryGrammar()->wrap('options->role_id');
    $table->unsignedInteger('role_id')->storedAs($role_id);
    $table->foreign('role_id')->references('id')->on('roles');
});
``

srry not sure what I'm doing wrong...thanks again.

**Comment by staudenmeir** [comment]
You can't access the relationship in `getOptionsAttribute()` because the result of this accessor is required for the relationship to work.

**Comment by greaterking** [comment]
....ah yes you're right Thanks!

But shouldn't \App\Role::find(2)->users work as well? I just get PHP Warning: array_key_exists() expects parameter 2 to be array, null given in P/vendor/laravel/framework/src/Illuminate/Support/Arr.php on line 151

I'm no longer doing anything in the accessor and have removed it. When doing   \App\Role::find(2)->users in tinker I get the error

**Comment by staudenmeir** [comment]
You need the accessor or a [JSON cast](https://laravel.com/docs/eloquent-mutators#array-and-json-casting).

**Comment by greaterking** [comment]
Just so I understand what do you mean by casting .. in Users model I'm trying to get the roles relationship. Per the example it only shows that `options` needs to be casted to json in the `User` model. So then in the `Role` model to get users what must be done other than

```
public function users()
{
    return $this->hasManyJson('App\User', 'options[]->role_id');
}
```

**Comment by staudenmeir** [comment]
This code works for me. When I remove `$casts`, I get the "PHP Warning: array_key_exists() expects parameter 2 to be array" error you mentioned earlier.

**Comment by greaterking** [comment]
ok I got it working it was an issue with my table seeders thanks!

**Comment by greaterking** [comment]
hmm some thing still seems off... 

I detached some things and continue to get the error to reproduce error:

two records in User
User id 1
options: `[{'role_id': 1, value: 'abc'}, {'role_id': 2, value: 'def'}, {'role_id': 4, value: 'ghi'}]`

User id 2
options: `[{'role_id': 4, value: 'abc'}, {'role_id': 5, value: 'def'}, {'role_id': 6, value: 'ghi'}]`

`\App\Role::find(4)->users` // it returns User 1 & 2 | ok
`\App\Role::find(6)->users` // it returns User 2       | ok
`\App\Role::find(2)->users` // it returns User 2       | ok

everything ok so far all relationships work...

When I do this:

\App\User::find(1)->roles()->sync([3 => ['value' => 'xyz']])->save() | ok

But now when I do this...

`\App\Role::find(3)->users ...results in ... PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /Users/ralphtheart/Sites/focus/vendor/laravel/framework/src/Illuminate/Support/Arr.php on line 151`

it should return User 1 but fails.

**Comment by staudenmeir** [comment]
What's the result of `\App\User::find(1)->getAttributes()['options']` after `sync()`?

**Comment by greaterking** [comment]
`[{"value": 'xyz', "account_field_id": 3}]`

**Comment by staudenmeir** [comment]
But `\App\User::find(1)->roles` works?

**Comment by greaterking** [comment]
hmmm actually no...it returns `null` hmm why is that? ... I see the json record in the database in the options column

**Comment by greaterking** [comment]
is it my schema?.. I have this

Schema::create('users', function (Blueprint $table) {
    $table->increments('id');
    $table->json('options');
    $role_id = DB::connection()->getQueryGrammar()->wrap('options->role_id');
    $table->unsignedInteger('role_id')->storedAs($role_id);
    $table->foreign('role_id')->references('id')->on('roles');
});

**Comment by staudenmeir** [comment]
Is it actually `'xyz'` (with single quotes)? Or `"xyz"`?

**Comment by greaterking** [comment]
In the db I see double quotes.

**Comment by staudenmeir** [comment]
What exact version of Laravel are you using?

Do you see single quotes in Laravel? How are you outputting the JSON value? With `echo`? Or `dd()`?

**Comment by staudenmeir** [comment]
Thanks, I found the issue. It's a bigger one...

**Comment by greaterking** [comment]
Ah ok thanks for looking into it...let me know how I can help.

**Comment by staudenmeir** [comment]
Check out the latest release, it should fix your issue.

**Comment by greaterking** [comment]
Working perfectly now! I'll let you know if I find anything else.
