### ISSUE TITLE
Trait method 'getAttribute' will not be applied, because it collides with 'Translatable'

### ISSUE THREAD

**Issue by DmitrySkibitsky** [staudenmeir/eloquent-json-relations#32]
What to do with it?

![2020-04-19_21-21](https://user-images.githubusercontent.com/20288556/79696180-c2dfe080-8283-11ea-9795-b0244e12d4b4.png)

**Comment by staudenmeir** [comment]
Please try this workaround: https://github.com/staudenmeir/eloquent-json-relations/issues/23#issuecomment-569498408

**Comment by DmitrySkibitsky** [comment]
> Please try this workaround: [#23 (comment)](https://github.com/staudenmeir/eloquent-json-relations/issues/23#issuecomment-569498408)

Thanks.

**Comment by DmitrySkibitsky** [comment]
Close
