### ISSUE TITLE
MariaDB json_contains parameter order

### ISSUE THREAD

**Issue by DominicSears** [staudenmeir/eloquent-json-relations#33]
Here's the issue that I'm having, it produces the code to where the function has the wrong parameter order.

Here's what I'm running:
mysql.exe  Ver 15.1 Distrib 10.4.11-MariaDB, for Win64 (AMD64), source revision 7c2c420b70b19cc02b5281127205e876f3919dad
Laravel Framework 7.8.1

Tables:
```
Schema::table('entities', function (Blueprint $table) {
    $table->id('grp_id');
    $table->json('leaders');
});
```

```
Schema::table('users', function(Blueprint $table) {
    $table->id();
    $table->text('name');
});
```

Example of Entities Table:

> id - 1
> leaders - [1, 3]

> id - 2
> leaders - [1]

Relationships:
```
class Entity extends Model
{
    protected $primaryKey = 'entities';
    protected $primaryKey = 'grp_id';

    use \Staudenmeir\EloquentJsonRelations\HasJsonRelationships;

    public function leaders()
    {
        return $this->hasManyJson(User::class, 'id', 'leaders')->distinct();
    }
}
```
```
use \Staudenmeir\EloquentJsonRelations\HasJsonRelationships;

class User extends Authenticatable
{
    use Notifiable, HasRoles, HasLocalDates, HasJsonRelationships;
    protected $casts = [
        'email_verified_at' => 'datetime',
        'leaders' => 'json',
    ];

    public function leaders()
    {
        return $this->belongsToJson(Entity::class, 'leaders');
    }
}
```

Called by:
`$entity = Entity::with('leaders')->get();`

Runs query:

> select distinct * from \`users\` where (json_contains(\`users\`.\`id\`, '\"[1, 3]\"') or json_contains(\`users\`.\`id\`, '\"[1]\"'))

When I dd():

> #relations: array:1 [▼
>         "leaders" => Illuminate\Database\Eloquent\Collection {#520 ▼
>           #items: []
>         }
>       ]

When I run it raw in the database it works by swapping the parameters of json_contains.
[https://mariadb.com/kb/en/json_contains/](url)

**Comment by staudenmeir** [comment]
You need to swap the relationships and move the JSON cast to the `Entity` model:

```php
class Entity extends Model
{
    use \Staudenmeir\EloquentJsonRelations\HasJsonRelationships;

    protected $primaryKey = 'grp_id';

    protected $casts = [
        'leaders' => 'json',
    ];

    public function leaders()
    {
        return $this->belongsToJson(User::class, 'leaders')->distinct();
    }
}

class User extends Authenticatable
{
    use Notifiable, HasRoles, HasLocalDates, HasJsonRelationships;

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function leaders()
    {
        return $this->hasManyJson(Entity::class, 'leaders');
    }
}
```

**Comment by DominicSears** [comment]
It worked, thank you for your help!

I apologize if this was something that came up before, I thought it was a unique problem to my situation after searching through the previously closed issues.

I hope this helps others who may face the same thing.
