### ISSUE TITLE
Has many with optional array items

### ISSUE THREAD

**Issue by dsazup** [staudenmeir/eloquent-json-relations#34]
Hey. Great package, I was really happy when I found this exists. I just tried to use it and run into an issue. I was not sure how to name it, but here it goes:

Let's say I have this relationship:

```php
public function conditionGroups()
{
     return $this->belongsToJson(Group::class, 'data->conditions[]->group->id');
}
```

And the `conditions` array contains:
```
[
    {group: {id: 1}, anotherKey: true},
    {group: {id: 2}, anotherKey: true},
    {field: {id: 1}, anotherKey: true},
    {field: {id: 2}, anotherKey: true}
]
```

I would expect the query to be `SELECT * FROM groups WHERE id IN(1,2)`, but what I actually see is `SELECT * FROM groups WHERE id IN(0,1,2)`. As you can see there is an additional zero coming from somewhere. Would you agree this is a bug?

**Comment by staudenmeir** [comment]
Yeah, that's a bug. The relationship expects every record in the array to actually have a foreign key. The ones without a key return `null` and Laravel converts them to zero.

**Comment by dsazup** [comment]
Cool, thanks for confirming. Unless you would like to fix it yourself, I could work on a PR to fix it 👍

**Comment by staudenmeir** [comment]
You're welcome to submit a PR.

**Comment by dsazup** [comment]
Fixed in #35.

**Comment by dsazup** [comment]
Hey @staudenmeir, any ideas when the fixed version will be released? Thanks.

**Comment by staudenmeir** [comment]
I wanted to wait with the release until I finish a new feature I'm working on because I didn't think it was urgent. I thought the bug would only cause incorrect results if related models with an `id` of `0` actually exist.

Are you getting incorrect results from the query?

**Comment by dsazup** [comment]
No, all good. No rush. Was really just wondering that is all. Thank you for the response.

**Comment by staudenmeir** [comment]
I've released the fix.
