### ISSUE TITLE
Query Performance

### ISSUE THREAD

**Issue by mstaack** [staudenmeir/eloquent-json-relations#36]
While using this brilliant package i noticed using gin indicies on the json columns
gives quite some improvement.

Should this be added to the docs?

**Comment by staudenmeir** [comment]
Absolutely. Can you share details, especially about the migration?

**Comment by mstaack** [comment]
this simple gin index made an improvement for me:
```
$table->jsonb('geo_type_ids')->nullable();
$table->gin('geo_type_ids');
```

without:
![image](https://user-images.githubusercontent.com/10169509/81313570-52f59680-9088-11ea-8a73-d2155530ad5f.png)

with:
![image](https://user-images.githubusercontent.com/10169509/81313644-6dc80b00-9088-11ea-9586-4b3b21c0fe36.png)

**Comment by staudenmeir** [comment]
`gin()` is not a native Laravel method, right? I can only create an index like this:

```php
$table->index('geo_type_ids', null, 'gin');
```

**Comment by mstaack** [comment]
ah yeah, i am using https://github.com/bosnadev/database/blob/157aab66ee2c3039df0df1d58f2022772b2c3ab0/src/Bosnadev/Database/Schema/Grammars/PostgresGrammar.php#L310 under the hood

**Comment by staudenmeir** [comment]
I've added a section to the README:
https://github.com/staudenmeir/eloquent-json-relations#query-performance

**Comment by mstaack** [comment]
sweet! keep up the great work 💪
