### ISSUE TITLE
Can't install on version 6

### ISSUE THREAD

**Issue by mlordi** [staudenmeir/eloquent-json-relations#37]
I have tried to use the command on the readme but I keep getting an error from composer.

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for staudenmeir/eloquent-json-relations v1.1 -> satisfiable by staudenmeir/eloquent-json-relations[v1.1].
    - Conclusion: remove laravel/framework v6.0.0
    - Conclusion: don't install laravel/framework v6.0.0

**Comment by staudenmeir** [comment]
Please share the whole error message. Are you using the command _with_ the double quotes?

**Comment by mlordi** [comment]
I will get it for you tomorrow but I used your command copied and pasted exactly.

**Comment by staudenmeir** [comment]
The command should work in all environments, but if it doesn't, you can explicitly specify the compatible package version:

```
composer require staudenmeir/eloquent-json-relations:"^1.3.2"
```
