### ISSUE TITLE
Can BelongsToManyJson be supported?

### ISSUE THREAD

**Issue by zishang520** [staudenmeir/eloquent-json-relations#39]
Due to some special circumstances, I know that it can be obtained through BelongsToJson, but the relationship of BelongsToJson is one-to-one

**Comment by staudenmeir** [comment]
What do your table schema and some sample data look like?

**Comment by zishang520** [comment]
> What do your table schema and some sample data look like?

- table:goods

| id  | category_ids  |title|
| ------------ | ------------ |-|
| 200  | [3, 6, 7, 8, 12]   |Test product one|
| 199  |  [11]|Test product two|
|198|[8]|Test product three|

- table:categories

|id|title|
| ------------ | ------------ |
|1|Home improvement|
|2|Education|
|3|Women's clothing|
|5|Men's clothing|
|6|Eat and drink|
|7|Mother and baby|
|8|Outdoor|
|10|3C|
|4|Pets|
|12|Toys|
|11|Beauty|
|9|Shoes and bags|

I need to get multiple category titles corresponding to the product.

**Comment by klaasgeldof** [comment]
You don't need BelongsToManyJson, you can achieve this already with:

```php
class Product extends Model
{
    use \Staudenmeir\EloquentJsonRelations\HasJsonRelationships;

    protected $casts = [
        'category_ids' => 'json',
    ];

    public function categories()
    {
        return $this->belongsToJson(Category::class, 'category_ids');
    }
}
```

```php
class Category extends Model
{
    use \Staudenmeir\EloquentJsonRelations\HasJsonRelationships;

    public function products()
    {
        return $this->hasManyJson(Product::class, 'category_ids');
    }
}
```

**Comment by zishang520** [comment]
I understand what you mean. I read the code. Although it implements related functions:
```php
<?php

namespace Staudenmeir\EloquentJsonRelations\Relations;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Arr;

class BelongsToJson extends BelongsTo
{
    use InteractsWithPivotRecords, IsJsonRelation;
```
BelongsTo is semantically different. In a laravel-based scaffold I used, BelongsTo was judged to be One To Many (Inverse), and I Need Many To Many (Inverse) to ensure the normal operation of the program.

Below is the code snippet of the scaffold:
```php
    public function render()
    {
        $relation = $this->model->{$this->name}();

        $renderable = $this->getNullRenderable();

        if ($relation    instanceof HasOne
            || $relation instanceof BelongsTo
            || $relation instanceof MorphOne
        ) {
            $model = $this->model->{$this->name};

            if (!$model instanceof Model) {
                $model = $relation->getRelated();
            }

            $renderable = new Show($model, $this->builder);

            $renderable->panel()->title($this->title);
        }

        if ($relation    instanceof HasMany
            || $relation instanceof MorphMany
            || $relation instanceof BelongsToMany
            || $relation instanceof HasManyThrough
        ) {
            $renderable = new Grid($relation->getRelated(), $this->builder);

            $renderable->setName($this->name)
                ->setTitle($this->title)
                ->setRelation($relation);
        }

        return $renderable->render();
    }
```

**Comment by staudenmeir** [comment]
> BelongsTo is semantically different. In a laravel-based scaffold I used, BelongsTo was judged to be One To Many (Inverse), and I Need Many To Many (Inverse) to ensure the normal operation of the program.

`BelongsTo` is one-to-many, but [`BelongsToJson`](https://github.com/staudenmeir/eloquent-json-relations#many-to-many-relationships) is many-to-many.

Have you tried @klaasgeldof's solution?

**Comment by zishang520** [comment]
> > BelongsTo is semantically different. In a laravel-based scaffold I used, BelongsTo was judged to be One To Many (Inverse), and I Need Many To Many (Inverse) to ensure the normal operation of the program.
> 
> `BelongsTo` is one-to-many, but [`BelongsToJson`](https://github.com/staudenmeir/eloquent-json-relations#many-to-many-relationships) is many-to-many.
> 
> Have you tried @klaasgeldof's solution?

BelongsToJson is many-to-many. But BelongsToJson inherits the BelongsTo object, so it is considered to be one-to-many, [source code](https://github.com/staudenmeir/eloquent-json-relations/blob/master/src/Relations/BelongsToJson.php#L11).

**Comment by staudenmeir** [comment]
> so it is considered to be one-to-many

By whom?

**Comment by zishang520** [comment]
> > so it is considered to be one-to-many
> 
> By whom?

laravel documentation: [https://laravel.com/docs/8.x/eloquent-relationships#one-to-many-inverse](https://laravel.com/docs/8.x/eloquent-relationships#one-to-many-inverse).

Source code of this project:[https://github.com/staudenmeir/eloquent-json-relations/blob/3bb8083606d4e05fdf0a1ce33338fc5e8f67ba2c/src/Relations/Postgres/BelongsTo.php#L8](https://github.com/staudenmeir/eloquent-json-relations/blob/3bb8083606d4e05fdf0a1ce33338fc5e8f67ba2c/src/Relations/Postgres/BelongsTo.php#L8)

I think the correct one should be: [https://laravel.com/docs/8.x/eloquent-relationships#many-to-many-model-structure](https://laravel.com/docs/8.x/eloquent-relationships#many-to-many-model-structure)

**Comment by staudenmeir** [comment]
I don't. `BelongsToJson` extends `BelongsTo` because it's technically much more similar to that class than to `BelongsToMany`. Despite the parent class, it in fact gives you a many-to-many relationship. You can't compare these JSON relationships to native relationships like that.

Have you tried @klaasgeldof's solution?

**Comment by zishang520** [comment]
> I don't. `BelongsToJson` extends `BelongsTo` because it's technically much more similar to that class than to `BelongsToMany`. Despite the parent class, it in fact gives you a many-to-many relationship. You can't compare these JSON relationships to native relationships like that.
> 
> Have you tried @klaasgeldof's solution?

I have tried it and the solution described by @klaasgeldof is feasible. The problem now is that in the laravel-based project I used, BelongsToMany and BelongsTo have different data processing methods. BelongsToJson inherits BelongsTo, but also has the ability of BelongsToMany objects, so can this ability be split?

**Comment by staudenmeir** [comment]
We aren't making any progress here. What's the actual issue?

- The package provides a solution for your situation.
- `BelongsToJson` extends from `BelongsTo` because it simplifies the implementation (this is not going to change). Despite that, `BelongsToJson` is completely different from `BelongsTo` (and `BelongsToMany`).

**Comment by zishang520** [comment]
If the database type is json `array[]`, it is recommended that `BelongsToJson` extend from `BelongsToMany`. For many-to-many associations, there is no need to create an intermediate table. Although the current `BelongsToJson` has this feature, I think it is inappropriate to extend from `BelongsTo`.

if you think my suggestion is feasible, I look forward to it.
