### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by indigoswann** [staudenmeir/eloquent-json-relations#4]
Great package, but I am having an issue with the hasManyJson relation. 

**Code**

```
public function recordings()
{
        return $this->hasManyJson(Recording::class, 'properties->device_id', 'device_id');
}
```

**DB Structure**
`properties field (JSON): {"device_id": "EF9FDEC"}`

**Error Returned**
`"Invalid argument supplied for foreach()", exception: "ErrorException",…}`

```
class: "Staudenmeir\EloquentJsonRelations\Relations\HasManyJson"
file: "/Users/greggushard/Valet/vss-portal/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php"
function: "buildDictionary"
line: 128
type: "->"
```

**Comment by staudenmeir** [comment]
This is a one-to-many relationship, right? `hasManyJson()` is meant for many-to-many relationships, use `hasMany()` instead.

**Comment by indigoswann** [comment]
i'm a moron.  thanks @staudenmeir great package again.  cheers
