### ISSUE TITLE
HasManyThroughJson

### ISSUE THREAD

**Issue by Intrflex** [staudenmeir/eloquent-json-relations#42]
I have three tables Organisation, Contact, Emails

my issues is im trying to get all the emails through client which maps like this client[id] -> contacts[client_id][email] -> contacts[to] but to is a json array of objects for example [{"name": "", "email": ""}] 

when I try 'to[]->email'  as my identifier it fails and is unable find anything yet to[]->email works elsewhere on has any son etc

I hope this makes sense I'm just wondering if there's a way to make this work

**Comment by staudenmeir** [comment]
Can you share the structure of all three tables?
