### ISSUE TITLE
Erro to get foreign keys, when has cast using Collection

### ISSUE THREAD

**Issue by maiconmva** [staudenmeir/eloquent-json-relations#47]
![image](https://user-images.githubusercontent.com/5194641/108844126-714a6580-75ba-11eb-9fdb-41589eabf576.png)

![image](https://user-images.githubusercontent.com/5194641/108844162-7c04fa80-75ba-11eb-9330-0df12316dde4.png)

Sample fix: 
![image](https://user-images.githubusercontent.com/5194641/108844435-e453dc00-75ba-11eb-8e9c-50709ddc4685.png)

    public function getForeignKeys(Model $model = null)
    {
        $model = $model ?: $this->child;

        if ($model->{$this->foreignKey} instanceof \Illuminate\Support\Collection) {
            $keys = $model->{$this->foreignKey}->toArray();
        } else {
            $keys = (array) $model->{$this->foreignKey};
        }

        return array_filter($keys, function ($key) {
            return $key !== null;
        });
    }

**Comment by staudenmeir** [comment]
Please share an example that lets me reproduce the issue.

**Comment by maiconmva** [comment]
In my model , the attribute Key used in relation is casted by collection, not array, so the problem occurs

**Comment by maiconmva** [comment]
hello, any news? 

u wanna i commit the fix?

**Comment by staudenmeir** [comment]
Yes, please create a PR.

**Comment by staudenmeir** [comment]
This has been fixed in `v1.5.4`.
