### ISSUE TITLE
Array of Objects "hasManyJson", "belongsTo" Got Empty Results

### ISSUE THREAD

**Issue by ragavanrandy** [staudenmeir/eloquent-json-relations#49]
Hi, I have created a repo to demonstrate my use case as follows : 
[ragavanrandy/staudenmeir-eloquent-json-relations-demo](https://github.com/ragavanrandy/staudenmeir-eloquent-json-relations-demo)

In my case, I have two models: **User and Order**.
The **Order** Model has **worklogs json field** to hold array of object and each object contains the **User** model **primary key**. 

The Order and User has relationship, To get the users of order and orders of user respectively.

**In User Model:** 

```
public function orders(){
    return $this->hasManyJson(Order::class, 'worklogs->[]->user_id', 'user_id');
}
```

**In Order Model:** 

```
public function user(){
    return $this->belongsToJson(User::class, 'worklogs->[]->user_id', 'user_id');
}
```

**In controller, jsonDemo.php:**

```
public function index(){
        $users = User::with('orders')->get();
        dd($users[0]);
    }

public function userOrders($id=null){
    if($id != null){
        $user = User::find($id);
        $user->load('orders');
        dd($user);
    }
}
```

**I got empty results in for relational models as follows:**

![getjson](https://user-images.githubusercontent.com/30138058/112950860-98331480-90ef-11eb-8d72-54074920799c.JPG)

![get_userorders](https://user-images.githubusercontent.com/30138058/112950852-9701e780-90ef-11eb-9cf2-0c19bb43ef0d.JPG)

**To reproduce this case,** 

- Mirror the [repo](https://github.com/ragavanrandy/staudenmeir-eloquent-json-relations-demo)
- install the packages using composer
- create database(**laraveljson**) and migrate tables 
- seed tables (DatabaseSeeder and OrderSeeder)
- serve the repo and visit,  http://localhost:8000/getjson and http://localhost:8000/get_userorders/{user_id}

**Comment by staudenmeir** [comment]
Remove the arrows from the left of the square brackets:

```php
public function orders(){
    return $this->hasManyJson(Order::class, 'worklogs[]->user_id', 'user_id');
                                                     ^^
}

public function user(){
    return $this->belongsToJson(User::class, 'worklogs[]->user_id', 'user_id');
                                                      ^^
}
```

**Comment by ragavanrandy** [comment]
After remove the arrows, it gives error as,

![Err remove arrow](https://user-images.githubusercontent.com/30138058/112994151-ced45380-911e-11eb-8f90-ee79135a7fb6.JPG)

**Comment by staudenmeir** [comment]
The demo works for me. What's the exception's stacktrace? What queries are executed?

What versions of PHP and MySQL are you using?

**Comment by ragavanrandy** [comment]
PHP : 7.4.15,
MySQL : 10.4.17-MariaDB

**Comment by ragavanrandy** [comment]
**Env :** 
PHP : 7.4.15
MySQL : 10.4.17-MariaDB

**Stacktrace :**
[link](https://flareapp.io/share/Bm06NgW7)

**Comment by staudenmeir** [comment]
The error is caused by your custom JSON cast, it needs to return associative arrays:

```php
return json_decode($value, true);
```

**Comment by ragavanrandy** [comment]
Thank you @staudenmeir. It's works like a charm.

**Comment by mkh71** [comment]
@staudenmeir my "hasManyJson" working perfectly but "belongsToJson" giving null value. 


class Service extends Model
{
    use HasFactory, uuids, HasJsonRelationships;
    protected $guarded = ['id'];
    public $incrementing = false;

    protected $casts = [
        'id' => 'string'
    ];

    public function panels(){
        return $this->hasManyJson(SubService::class , 'service_id')->where('status' , 1);
    }
}


class SubService extends Model
{
    use HasFactory, uuids, HasJsonRelationships;
    protected $guarded = [];
    public $incrementing = false;
    protected $casts = [
        'service_id' => 'json',
        'id' => 'string'
    ];

    public function service(){
        return $this->belongsToJson(Service::class , 'service_id' );
    }
}

and in database data are saved like: "[\"6962c9e0-5c60-11ed-aa01-21826e842cac\"]".  If I remove "" before & after [], then belongsToJson works fine, but json_decode giving error. 
What is actual way to show data data through belongsToJson from SebService model or to save data in database?
