### ISSUE TITLE
Support in laravel 7 and 8?

### ISSUE THREAD

**Issue by FuriosoJack** [staudenmeir/eloquent-json-relations#50]
Hello, I am working on a project in laravel 7 and this package would be of great help to me. But it has no support for laravel 7 :(
I don't know if you could put the support for laravel 7 or I could help you that you would need me to check your package with the updates of laravel so I can fork and help the update-

**UPDATE**
_I started to navigate in their tags and I realized that I must use version 1.4. * However, they should specify in their composer.json that they support database8 and 7 since if people who use laravel 8 make updates we will not have the updates_

**Comment by FuriosoJack** [comment]
Thanks

**Comment by staudenmeir** [comment]
> However, they should specify in their composer.json that they support database8 and 7 since if people who use laravel 8 make updates we will not have the updates

The package has separate versions for each version of Laravel and new features or bug fixes can/will be back backported for Laravel 6 and 7. Is that what you mean?
