### ISSUE TITLE
SQLServer 2019 does not get the flatten json ids

### ISSUE THREAD

**Issue by ahmadmayahi** [staudenmeir/eloquent-json-relations#54]
I have the following relationship:

```php
return $this->belongsToJson(Scheme::class, 'scheme_ids');
```

The `scheme_ids` is of type `varchar` but contains some JSON ids as follows:
```json
[
    1,
    2,
    3
]
```

The relationship generates the following SQL:

```sql
SELECT
	[schemes].[name],
	[schemes].[id]
FROM
	[schemes]
WHERE
	[schemes].[id] in(0)
```

Why it returns `in(0)` instead of the `scheme_id` data?

**Comment by staudenmeir** [comment]
Please share both models and their migrations.
