### ISSUE TITLE
Updating/Saving the one-to-many relationship

### ISSUE THREAD

**Issue by boryn** [staudenmeir/eloquent-json-relations#56]
Looking at the example from Readme with User and 'locale_id' kept in \`options\` - actually how can we update the user's locale_id?

We can easily read $user->locale, but how to update it?

And how does updating work? I mean if \`options\` kept other attributes like for example 'currency', will setting just one of the attributes leave untouched the other attributes already present in the db?

**Comment by staudenmeir** [comment]
You can update it with Laravel's native `associate()` and `save()`: 
https://laravel.com/docs/8.x/eloquent-relationships#updating-belongs-to-relationships
This will change the value of `locale_id` and then update the whole `options` array in the database.

You can also update the value of `locale_id` directly in the database:
https://laravel.com/docs/8.x/queries#updating-json-columns

Both methods leave other attributes untouched.
