### ISSUE TITLE
belongsTo not working with array

### ISSUE THREAD

**Issue by ThiagoLovatine** [staudenmeir/eloquent-json-relations#6]
**Here's my json, the field name is "payload":** 
`{"icon": "img/categorias/automotivo.png", "route": "website.listaLocais", "routeParams": {"slug": "automotivo"}}`

**My relationship, slug is the field name on the parent table:**
`return $this->belongsToJson(Category::class, 'slug', 'payload->routeParams[]->slug');`

**I've also tried:**
`return $this->belongsToJson(Category::class, 'slug', 'payload[]->routeParams[]->slug');`
`return $this->belongsToJson(Category::class, 'slug', 'payload->routeParams->slug');`

Is what I'm trying to achieve not supported at the moment or I'm just not doing it right?

**Comment by staudenmeir** [comment]
The relationship requires `routeParams` to be an array:

```json
{"icon": "img/categorias/automotivo.png", "route": "website.listaLocais",
  "routeParams": [{"slug": "automotivo"}]}
                 ^                      ^
```

Is `payload` an attribute in the `Category` model?

**Comment by ThiagoLovatine** [comment]
That's right, created like this $table->json('payload');

**Comment by staudenmeir** [comment]
You'll have to use the inverse relationship:

```php
public function categories() {
    return $this->hasManyJson(Category::class, 'payload[]->routeParams[]->slug', 'slug');
}
```

**Comment by staudenmeir** [comment]
Does it work for you?

**Comment by ThiagoLovatine** [comment]
I didn't work, I copied your code at first, but also change to this:

public function option() {
```
    return $this->hasManyJson(Category::class, 'payload->routeParams[]->slug', 'slug');
}
```
and this 
```
public function option() {
    return $this->hasMany(Category::class, 'payload->routeParams[]->slug', 'slug');
}
```

**Comment by staudenmeir** [comment]
I see, I thought there can be multiple categories.

Use this and the original JSON data (`"routeParams": {"slug": "automotivo"}`):

```php
public function category() {
    return $this->hasMany(Category::class, 'payload->routeParams->slug', 'slug');
}
```

**Comment by staudenmeir** [comment]
Does it work for you?

**Comment by ThiagoLovatine** [comment]
No, the error is gone, but it doesn't find the relationship.

**Comment by staudenmeir** [comment]
How are you using the relationship?

**Comment by ThiagoLovatine** [comment]
I had to give up since the deadline is soon, when I finish I'll get back to this and try again, but thanks anyway it help me understand a bit more about how the package works.

**Comment by staudenmeir** [comment]
Can I close this?
