### ISSUE TITLE
Simple hasMany relation does not work 

### ISSUE THREAD

**Issue by gguney** [staudenmeir/eloquent-json-relations#61]
Version: "v1.4.3"
Laravel Version: "v7.30.4"
Mysql Version: "5.7.31"

Here is my code and db structure. 

Simply, there is a game team and it has json column called user_ids. Inside of the user_ids there are multiple user ids.

Also casting user_ids as json inside my model
`    protected $casts = ['user_ids' => 'json']`

<img width="523" alt="Screen Shot 2021-07-17 at 07 37 08" src="https://user-images.githubusercontent.com/16459896/126025646-bd6a8150-0031-4d95-83b1-bac73c882210.png">

<img width="674" alt="Screen Shot 2021-07-17 at 07 38 00" src="https://user-images.githubusercontent.com/16459896/126025648-15944915-3654-44ca-b890-4ebae66f7227.png">

Here is the tinker output

<img width="386" alt="Screen Shot 2021-07-17 at 07 53 17" src="https://user-images.githubusercontent.com/16459896/126026044-7b306c27-9fac-42fe-9f0c-91644e0b97b0.png">

**Comment by staudenmeir** [comment]
This case requires a many-to-many relationship:
https://github.com/staudenmeir/eloquent-json-relations#array-of-objects

```php
public function users()
{
   return $this->belongsToJson('App\User', 'user_ids[]->id');
}
```

**Comment by gguney** [comment]
Thank you for your response. After searching and thinking I found another solution: 

`    public function users()
    {
        return $this->belongsToJson(User::class, 'user_ids[]->id');
    }
`

Not so different from yours :) 

I think getting the class name from model itself like 'User::class' is better solution rather than 'App\User'. Just a little touch :)
