### ISSUE TITLE
Sort the result in json

### ISSUE THREAD

**Issue by sbc640964** [staudenmeir/eloquent-json-relations#62]
Does it belong to arrange the result in the local key in json
What I see is that it creates a new key in the model

**Comment by staudenmeir** [comment]
Please share the relationship and the code of query that uses the relationship.

**Comment by sbc640964** [comment]
Page.php

```php
public function baseCollection ()
{
    return $this->hasOne(Collection::class, 'id', 'data->baseCollection');
}
```

PageController.php
```php
Page::with('base_collection')->find(1);
```

The result of the relationship is at the root of the model instead of in json data

**Comment by staudenmeir** [comment]
> The result of the relationship is at the root of the model instead of in json data

How do you mean that? What's the expected vs. actual result?
