### ISSUE TITLE
belongsToJson with nested multi level depth not working

### ISSUE THREAD

**Issue by nogamenofun98** [staudenmeir/eloquent-json-relations#64]
I using eager loading to load the json relationship.
My data in the column named "joined_product_json" look like this: 
`[
    {
        "id": 872,
        "sub_prod": [
            {
                "id": 867,
                "discount_percent": "30"
            },
            {
                "id": 866,
                "discount_percent": "25"
            }
        ],
        "main_discount_percent": "10"
    },
    {
        "id": 857,
        "sub_prod": [
            {
                "id": 849,
                "discount_percent": "50"
            },
            {
                "id": 848,
                "discount_percent": "55"
            }
        ],
        "main_discount_percent": "15"
    }
]`

my relationship defined as like this: `return $this->belongsToJson(Product::class, "joined_product_json[]->sub_prod[]->id");`

but it return error when i access the model: 
`array_key_exists() expects parameter 2 to be array, null given`

The exception stack show here, the $record is null: 
![image](https://user-images.githubusercontent.com/9070825/130048365-5f92f16e-d81e-4ad0-bae2-19b6641fd294.png)

Is my method of defining the relationship wrong? 

Update 1: 
![image](https://user-images.githubusercontent.com/9070825/130047958-47eb75b7-9aa6-44f1-8570-e86340584579.png)
It seem like can get the Product model that I saved in the sub_prod json, look at that "848" id, is match with my sample data

**Comment by staudenmeir** [comment]
The package doesn't support relationships with two nested arrays (`[]` twice in the JSON path) and I'm not sure if that would even be possible.

**Comment by nogamenofun98** [comment]
hmm okay understand, I try modify the data structure
