### ISSUE TITLE
Using belongsToJson returns nested array.

### ISSUE THREAD

**Issue by muhammedkaraoglu** [staudenmeir/eloquent-json-relations#65]
Hello, first of all, I would like to state that I am writing with google translate.

**Model** using belongsToJson
<img width="543" alt="Ekran Resmi 2021-09-02 16 30 23" src="https://user-images.githubusercontent.com/25641500/131852415-b5d1a317-91b8-449b-b21a-be726cccdf9e.png">

**Query**
<img width="623" alt="Ekran Resmi 2021-09-02 16 31 13" src="https://user-images.githubusercontent.com/25641500/131852537-d8bb46c4-f2f5-45d8-aa3e-706eda8f0cdb.png">

**Output**
<img width="481" alt="Ekran Resmi 2021-09-02 16 32 11" src="https://user-images.githubusercontent.com/25641500/131852702-bdf5ad4e-87f3-41de-a565-0d8e1280d301.png">

#### But when using belongsTo, the output is as follows.

<img width="575" alt="Ekran Resmi 2021-09-02 16 34 11" src="https://user-images.githubusercontent.com/25641500/131852986-6127098f-2466-4c15-b1fc-f7bd28909f28.png">

**May I know what is the reason for this?**

**Comment by staudenmeir** [comment]
`belongsToJson()` is for many-to-many relationships, that means when an accident has multiple city IDs.

In your case with only one city per accident, `belongsTo()` is the correct relationship.
