### ISSUE TITLE
Error during installation in Laravel 8

### ISSUE THREAD

**Issue by javad3d** [staudenmeir/eloquent-json-relations#66]
PS D:\Desktop\clerk> composer require "staudenmeir/eloquent-json-relations:^1.1"
./composer.json has been updated
Running composer update staudenmeir/eloquent-json-relations
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires staudenmeir/eloquent-json-relations 1.1 -> satisfiable by staudenmeir/eloquent-json-relations[v1.1].
    - staudenmeir/eloquent-json-relations v1.1 requires illuminate/database ~5.5.29|5.6.*|5.7.* -> found illuminate/database[v5.5.33, ..., 5.7.x-dev] but these were not loaded, likely because it conflicts with another require.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by Dutchman1990** [comment]
Having the same issue with laravel `framework 8.40`.
Heres my terminal op. 

`./composer.json has been updated`
`Running composer update staudenmeir/eloquent-json-relations`
`Loading composer repositories with package information`
`Updating dependencies`
`Your requirements could not be resolved to an installable set of packages.`

  `Problem 1
    - Root composer.json requires staudenmeir/eloquent-json-relations 1.1 -> satisfiable by staudenmeir/eloquent-json-relations[v1.1].   
    - staudenmeir/eloquent-json-relations v1.1 requires illuminate/database ~5.5.29|5.6.*|5.7.* -> found illuminate/database[v5.5.33, ..., 5.7.x-dev] but these were not loaded, likely because it conflicts with another require.`

**Comment by staudenmeir** [comment]
> Installation command provided here try to install a version which is not compatible with latest version of laravel. Check here for version guide in composer command.

That's what the `^` is for. This way, the installation command works for all versions of Laravel. For Laravel 8, it installs the package's latest version.

There are very rare cases where the `^` seems to be ignored by Composer. What OS and terminal are you two using?

**Comment by Dutchman1990** [comment]
@staudenmeir I am using `windows 10 Pro` and `composer  2.0`. I have tried with ms powershell integrated with vscode. Did not tried with other terminal though.  Mine got v1.5 after removing ^.

**Comment by staudenmeir** [comment]
Thanks, I can reproduce it now. This is a PowerShell issue, the caret needs to be escaped:

```
composer require "staudenmeir/eloquent-json-relations:^^^^1.1"
```

I'll add a note the README.
