### ISSUE TITLE
How to work with pivot data

### ISSUE THREAD

**Issue by angelkurten** [staudenmeir/eloquent-json-relations#7]
I'm column json with price type and value

`"prices": [{
		"id": 1,
		"value": 5000
	}, {
		"id": 2,
		"value": 30000
	}],`

**Comment by staudenmeir** [comment]
Have you looked at https://github.com/staudenmeir/eloquent-json-relations#array-of-objects?

**Comment by angelkurten** [comment]
`public function prices_eloquent()
    {

        return $this->belongsToJson(PriceType::class, 'prices[]->price_type_id');
    }`

Yes, only get Prices Type model without pivot data

**Comment by staudenmeir** [comment]
Are you using the package's latest version `v1.1.3`?

Please add both models, their migrations and some sample data.

**Comment by angelkurten** [comment]
Response object product -> [https://prnt.sc/mpzt99](https://prnt.sc/mpzt99)

`$product = \App\Models\Product::find(1);
    dd($product->prices_eloquent->pivot);`

Get error -> "Property [pivot] does not exist on this collection instance."

`$product = \App\Models\Product::find(1);
    dd($product->prices_eloquent->pivot());`

 Get error "Method Illuminate\Database\Eloquent\Collection::pivot does not exist."

**Comment by angelkurten** [comment]
> Are you using the package's latest version `v1.1.3`?
> 
> Please add both models, their migrations and some sample data.

Yes, version 1.1.3

**Comment by staudenmeir** [comment]
The collection itself can't have a `pivot` relationship, the individual models do:

```php
foreach ($product->prices_eloquent as $price) {
    dd($price->pivot);
}
```

**Comment by angelkurten** [comment]
Thanks for help
