### ISSUE TITLE
withExists('column') Always returns false

### ISSUE THREAD

**Issue by navaneeth-raman-bhaskar** [staudenmeir/eloquent-json-relations#71]
**Country.php**
```

public function languages(): BelongsToJson
{
    return $this->belongsToJson(Language::class, 'languages[]->id', 'id');
}
```
In controller
```
$countries=Country::withExists('languages AS has_language')->get();

$has = $countries()->first()->has_language
```

> $has is  always false even if country has languages.

**Comment by staudenmeir** [comment]
What's the result of `dd($countries->first()->getAttributes());`?

**Comment by navaneeth-raman-bhaskar** [comment]
@staudenmeir 
 ```
array:7[
  "id" => 1
  "name" => "India"
  "created_at" => "2021-12-02 13:12:04"
  "updated_at" => "2021-12-02 13:14:04"
  "deleted_at" => null
  "languages" => "[{"id": "1", "id":"2"}]"
  "has_language" => 0
]
```

**Comment by staudenmeir** [comment]
The types have to match between local and foreign key. The IDs in the JSON array need to be integers instead of strings:

    "languages" => "[{"id": 1, "id": 2}]"

**Comment by navaneeth-raman-bhaskar** [comment]
@staudenmeir  `Country::with('languages')->get();` works perfectly fine. Doesn't it need same type then?

**Comment by staudenmeir** [comment]
Queries like eager loading also work with integer strings because the values are loosely compared in Laravel/PHP.

Queries like `withExists()` are comparing the values directly in the database which is stricter and doesn't accept different types.

**Comment by navaneeth-raman-bhaskar** [comment]
@staudenmeir ok I will close the issue
