### ISSUE TITLE
Any ideas on how to integrate this for an array of integer of type integer[] in postgre?

### ISSUE THREAD

**Issue by raphaelmsr** [staudenmeir/eloquent-json-relations#72]
Hello !
Has anyone managed to do a HasMany relation on a model with a join on a array of ints?
Usually like a.id = ANY(b.ids)

Thanks in advance! Went from json to simple arrays on this matter, performs better somehow

**Comment by staudenmeir** [comment]
I had looked into this at some point, but didn't pursue it any further since only PostgreSQL supports it.

Do you have any performance benchmarks that compare native array with JSON arrays?

**Comment by raphaelmsr** [comment]
I didnt time any benchmark when shifting to int arrays but it did dramatically somehow unbloat my whole project.
Im guessing the JSONB footprint and the sizes were too big for such an operation like @>
Even with the GIN index with jsonb path ops it was waaaay too slow
Postgre14 + integer arrays saved my delivery
I tried to look into the source code myself and make a PR out of it but couldnt find anywhere the @> mention
It is just a matter of inverting the equality and putting an ANY instead

Thanks for your reply!! Always there for the community I see 😊

**Comment by staudenmeir** [comment]
How are handling arrays in your model(s)? Do you have a cast like `array` for JSON arrays?

**Comment by raphaelmsr** [comment]
I created a new column of type integer[]
So the jsonb columnb went from [1,2,3] to {1,2,3}
And what i used to do with this plugin was

[1,2,3]::jsonb @> jsonb_build_array(id)

What i do know is

id = ANY({1,2,3})



>

**Comment by raphaelmsr** [comment]
And I removed the cast json from the model déclaration in Laravel yes

>

**Comment by raphaelmsr** [comment]
Ended up duplicating the column just for the Laravel model in order to benefit from whereHas on the eloquent model !
