### ISSUE TITLE
Is there support for Arabic ?

### ISSUE THREAD

**Issue by ahmadsaadkhan** [staudenmeir/eloquent-json-relations#74]
My table collations is utf8_general_ci same for my column but when I save data to MySQL it saves as below,

{"returnedFromValue":"\u0627\u0644\u0645\u0639\u0627\u062f\u0649<br\/>"}{"returnedFromValue":"\u0627\u0644\u0645\u0639\u0627\u062f\u0649<br\/>"}

Need Solution like this 
echo json_encode($value, JSON_UNESCAPED_UNICODE);

**Comment by ahmadsaadkhan** [comment]
My question is how I will unescape the Unicode when saving JSON encoded data to DB echo json_encode($value, JSON_UNESCAPED_UNICODE); is used to write Arabic to the MySQL column, How I will unescape the array I am passing to desired function check example below.

$user->roles()->sync([1 => ['active' => 'نص الاختبار'], 3 => ['active' => 'نص الاختبار']])->save();

**Comment by staudenmeir** [comment]
This is Laravel's native JSON casting. Try overriding `asJson()` in your model:

```php
class Role extends Model
{
    protected $casts = [
        'options' => 'json',
    ];

    protected function asJson($value)
    {
        return json_encode($value, JSON_UNESCAPED_UNICODE);
    }
}
```

**Comment by ahmadsaadkhan** [comment]
This worked thanks @staudenmeir
