### ISSUE TITLE
In laravel Nova, using ->fields() to add fields for the pivot data is not working with belongsToJson() relation

### ISSUE THREAD

**Issue by MuathIbnHassan** [staudenmeir/eloquent-json-relations#76]
In Laravel Nova, Using ```\Laravel\Nova\Fields\BelongsToMany``` as a field for the relation ```belongsToJson``` is working fine except for the pivot data

With ```\Illuminate\Database\Eloquent\Relations\BelongsToMany```, the pivot data's fields can be displayed using [->fields()](https://nova.laravel.com/docs/3.0/resources/relationships.html#pivot-fields) method.

Currently ```->fields()``` is NOT working with ```\Staudenmeir\EloquentJsonRelations\Relations\BelongsToJson```

```Php
BelongsToMany::make('Roles')
    ->fields(
        fn() => [
            Text::make('Notes'),
        ]
    ),
```

**Comment by staudenmeir** [comment]
I don't have Nova so I can't test this.

> Currently ->fields() is NOT working with \Staudenmeir\EloquentJsonRelations\Relations\BelongsToJson

How exactly is it not working? Is there an error? What's the error message?

**Comment by MuathIbnHassan** [comment]
hi, the ->fields() method accepts a callback as a parameter and stores the callback in a property called ```fieldsCallback``` _The callback that should be used to resolve the pivot fields_

The issue is that the callback never runs and the fields added will not be shown in the relation, no errors or exception

nova is needed to resolve this, it`s more of a future request than an issue

I will look into it again and try to figure out why it's not working

**Comment by staudenmeir** [comment]
Can you share the code of Nova's `fields()` method?
