### ISSUE TITLE
It's realy required?

### ISSUE THREAD

**Issue by titch-ane** [staudenmeir/eloquent-json-relations#8]
Since you change requirements from `"illuminate/database": "~5.5.29|5.6.*|5.7.*",` to `"illuminate/database": "5.8.*"` all systems that works with 5.7 and lower became unsupported. This is not like "added support 5.8" but "5.7 <= support removed".

Also
```
"require-dev": {
        "laravel/homestead": "^7.18",
        "phpunit/phpunit": "~6.5"
    },
```

there are not necessary for workability and may be moved to `suggest` section.

**Comment by staudenmeir** [comment]
The package still supports all versions of Laravel. Release `v1.1.3` offers all the latest  features for Laravel < 5.8 and will receive bug fixes.
