### ISSUE TITLE
hasManyJson giving null results and belongsToJson working fine.

### ISSUE THREAD

**Issue by aman-2896** [staudenmeir/eloquent-json-relations#81]
First of all thanks for such an amazing package. It has really made some tasks very easy.
However I am facing this problem which I've explained in detail here  [Stackoverflow](https://stackoverflow.com/questions/72542012/unable-to-fetch-results-from-hasmanyjson-using-staudenmeir-eloquent-json-relat)
The belongsToJson relation is working completely fine.

**Comment by aman-2896** [comment]
So what can be done here, and why belongstojson relationship is working fine with the same ids

**Comment by staudenmeir** [comment]
> So what can be done here

You need to convert all the IDs in your JSON to integers: `[{"id": 11, ...}]`

> why belongstojson relationship is working fine with the same ids

Some of the `BelongsToJson` queries work because, here, IDs are compared in PHP which is looser than `HasManyJson`'s comparison inside the database.

**Comment by aman-2896** [comment]
You're right, when I convert them, it started working again. Thanks for the help ;)
