### ISSUE TITLE
Be able to define Relationships with multiple keys instead of just one

### ISSUE THREAD

**Issue by didac-adria** [staudenmeir/eloquent-json-relations#82]
Hey!

Lovely package, thanks for sharing.

I've just found out a case which could be interesting for other people. Currently, in Laravel relationships, you can pass an array of keys when defining the relationship to another table. Instead of looking for the id only in the related table, it will look for all the values specified in the array of keys of the relationship. Nevertheless, the current implementation of this package doesn't allow us to pass an array of keys to query for. For example, the BelongsToJson relationship allows only strings as foreighKey and ownerKey.

Implementation for this package:
![image](https://user-images.githubusercontent.com/63950600/174847732-9a01f486-59d4-4f0e-b5c0-f8a2bea89b20.png)

Implementation for the Laravel standard relationships:
![image](https://user-images.githubusercontent.com/63950600/174847887-d3fcccda-9884-4bb9-86ed-a63967373c59.png)

In my case, I'm trying to define a relationship to a table which contains repeated id records. So, to find the correct ones, I need to look for the id but also team_id to get the correct resources. I can't define the relationship only with the id with the other table.

That could be a nice feature!

**Comment by staudenmeir** [comment]
Hi @didac-adria,
What do the migrations of both your tables look like? Please also share some sample data.

Supporting multiple keys is quite complex, that's also why https://github.com/topclaudy/compoships only works with the [simplest Laravel relations](https://github.com/topclaudy/compoships#supported-relationships).

**Comment by didac-adria** [comment]
Oh I forgot to mention compoships! Yes, I know that only works with simplest relationships. But I thought that, in reality this is a "simple" relationship where the only difference is that we save multiple id keys in an array. So that could be possible. But I say that without haven't dug too much into how this could be done, so I could be wrong.

Regarding migrations, we don't save migrations. We [squash migrations](https://laravel.com/docs/9.x/migrations#squashing-migrations). But I can share the columns schema.

This is the table where we want to put the relationship. The "rentals" column is the one containing the json with the id's to the rentals this settlement refers to:
<img width="781" alt="image" src="https://user-images.githubusercontent.com/63950600/174977369-f7ada400-40b2-4b9a-8717-57804f098105.png">

And this is the schema of the rentals table. I just cut some columns wich are irrelevant for this topic. As there might be multiple id's in this table, to find a rental in this table, we query by id and team_id:
<img width="623" alt="image" src="https://user-images.githubusercontent.com/63950600/174977749-c3767cad-8e1b-4e37-a7fd-5bb4b725d71a.png">
<img width="519" alt="image" src="https://user-images.githubusercontent.com/63950600/174977796-68678154-675d-4b1a-980e-d4d2c02c946f.png">

**Comment by didac-adria** [comment]
Great news thank you!
