### ISSUE TITLE
Relationship doesn't working

### ISSUE THREAD

**Issue by jetao** [staudenmeir/eloquent-json-relations#9]
What I trying to achieve is get the relationship between "Stock" and "Supply" model.
I tried to use these parameters but didn't work.
```
public function supplies()
{
  return $this->belongsToJson('App\Supply', 'supplies->[]->supply->id');
}
```

The column which stores the JSON is "supplies" and it has this format:
```
[
  {
    "supply": {
      "id": 1,
      ...
    },
    "price": "1",
    "quantity": "5"
  },
  {
    "supply": {
      "id": 2,
      ...
    },
    "price": "1",
    "quantity": "10"
  }
]
```

**Comment by staudenmeir** [comment]
There are multiple issues:
- The syntax is not correct: It's `'supplies[]->...'`, not `'supplies->[]->...'`.
- A relationship can't have the same name as an attribute.
- This kind of nested path not supported (yet). This would work: `'supplies[]->supply_id'`

**Comment by jetao** [comment]
I changed these issues and it still doesn't work.

```
public function test() {
  return $this->belongsToJson('App\Supply', 'supplies[]->supply_id');
}
```
Its giving error when i try call this: 
```
`$stocks = StockControl::with('destination')->whereHas('test', function($query) use ($supplies) {
      $query->whereIn('id', $supplies);
});
```
Error:
`
SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "supply_id" (SQL: select count(*) as aggregate from "stock_control" where exists (select * from "supplies" where ("stock_control"."supplies")::jsonb @> jsonb_build_array(jsonb_build_object(1::text, "supplies"."id")) and "id" in (2, 3, supply_id)) and exists (select * from "stock_entry" where "stock_control"."id" = ("stock_entry"."stock_control_id")::int and "destination_id" in (1, 2)) and exists (select * from "stock_exit" where "stock_control"."id" = ("stock_exit"."stock_control_id")::int and "origin_id" in (1, 2)) and exists (select * from "stock_requisition" where "stock_control"."id" = ("stock_requisition"."stock_control_id")::int and ("destination_id" in (1, 2) or "origin_id" in (1, 2))) and exists (select * from "stock_transference" where "stock_control"."id" = ("stock_transference"."stock_control_id")::int and ("destination_id" in (1, 2) or "origin_id" in (1, 2))))
`

**Comment by staudenmeir** [comment]
Thanks, this is indeed a bug. The latest release fixes it.

**Comment by jetao** [comment]
Hello,
the error was solved, but when I try to get the related items its return an empty array.
`return StockControl::first()->items;`
```
public function items()
{
  return $this->belongsToJson('App\Supply', 'supplies[]->supply_id');
}
```

**Comment by staudenmeir** [comment]
What's the value of `StockControl::first()->supplies`?

**Comment by jetao** [comment]
```
array:1 [▼
  0 => array:4 [▼
    "supply" => array:16 [▼
      "id" => 2
      "name" => "Alfinete cabeça colorida [50 unidades]"
      "unit" => "CX"
      "brand" => array:4 [▶]
      "group" => array:5 [▶]
      "bar_code" => null
      "brand_id" => 3
      "group_id" => 3
      "supplier" => null
      "created_at" => "2019-01-28 11:37:23"
      "updated_at" => "2019-01-28 11:37:23"
      "ideal_stock" => null
      "manufacturer" => array:4 [▶]
      "maximal_stock" => null
      "minimal_stock" => null
      "manufacturer_id" => 3
    ]
    "ordered" => "10"
    "quantity" => 2
    "max_quantity" => 0
  ]
]
```

**Comment by staudenmeir** [comment]
Your JSON data has to match the new selector:

```json
[
  {
    "supply_id": 1,
  },
  {
    "supply_id": 2,
  }
]
```

**Comment by jetao** [comment]
So I can't access the property id inside object supply? Because it's in production and I can't change the structure.

**Comment by staudenmeir** [comment]
No, this is not possible at the moment. I will check whether it's possible to support that.

**Comment by jetao** [comment]
Ok, thanks for helping!

**Comment by staudenmeir** [comment]
The latest release adds support for your relationship with `'supplies[]->supply->id'`.
