### ISSUE TITLE
Not an issue, really need a help 

### ISSUE THREAD

**Issue by emmaMinty12** [staudenmeir/eloquent-json-relations#90]
Hello @staudenmeir 

I really love this package, it really helps beginners like me
I'm here from one of the StackOverflow thread's replies, I found this amazing package

recently I've used this in one of my projects

Currently, I'm facing a huddle and don't get any idea how to overcome

Tables:

```
skills
-------------
- id
- title
- parent id
-------------
```

```
user
-------------
- id
- skills (here it is a JSON)
-------------

```

My JSON looks like this: 

`[{"category": "1", "sub-category": ["1", "2", "3"]}, {"category": "2", "sub-category": ["1", "4", "5"]}]`

In user model:

```
public function Skills()
{
    return $this->belongsToJson(Skill::class, 'skills[]->category', "parent_id");
}
```

in skill model:

```
public function subCategory()
{
   return $this->belongsToJson(Skill::class, 'skills[]->sub-category','parent_id');
}
```

QUERY:
```
User:: with('Skills' => function($q){
                    $q->with(['subCateogry']);
                }]);
```

RESULT:
---------------------
```
{
  "id": 1,
  "title": "furniture repair",
  "parent_id": 0,
  "sub": [], // here not getting the sub-category list 
   }
}
```

as far as I'm able to get the category title, but failed with getting the sub-category title.

could you or anybody please help me with this, I think I tried many ways but seems fails

I've been trying for 2 days to work but no luck.

 Am I going in the right direction? Any help would be great!

**Comment by staudenmeir** [comment]
Hi @emmaMinty12,

> [{"category": "1", "sub-category": ["1", "2", "3"]}, {"category": "2", "sub-category": ["1", "4", "5"]}]

The package doesn't support a structure like this that has nested arrays, you need to find a different approach.

**Comment by emmaMinty12** [comment]
Ohh :(

thanks for your reply
