### ISSUE TITLE
has and WhereHas doesn't work

### ISSUE THREAD

**Issue by bgarrison25** [staudenmeir/eloquent-json-relations#92]
So I have a Users table that has a field called "failures" thats a json array of id's from another table. 

I created my relationship like so:

`    public function activeFailures()
    {
        // $failures = $this->failures ?? [];
        // $warnings = $this->warnings ?? [];
        // $issues = array_merge($failures, $warnings);
        return $this->hasMany('App\MeterHealthCheckAudit', 'id', 'failures'); //->whereIn('id', $issues);
    }
`

It WORKS!!.....however as soon as I go to use whereHas() or has() it just returns null.

**Comment by staudenmeir** [comment]
Hi @bgarrison25,
It looks like you need to define a [`BelongsToJson`](https://github.com/staudenmeir/eloquent-json-relations#array-of-ids) relationship:

```php
class User extends Model
{
    use \Staudenmeir\EloquentJsonRelations\HasJsonRelationships;

    protected $casts = [
       'failures' => 'json',
    ];
    
    public function roles()
    {
        return $this->belongsToJson(MeterHealthCheckAudit::class, 'failures');
    }
}
```
