### ISSUE TITLE
One dimensional array

### ISSUE THREAD

**Issue by NomisGnos** [staudenmeir/eloquent-json-relations#93]
I have a JSON field for a model that saves the data into the database like this:

["1", "5", "10"]

The User model is setup for `$table->json('units')->nullable();`

However, how do I set that up with belongsToMany or belongsTo?  Because the pointer in your readme seems to require it but laravel seems to be saving this as just a single dimentional array.

**Comment by staudenmeir** [comment]
Hi @NomisGnos,
This is the README section that's relevant for you: https://github.com/staudenmeir/eloquent-json-relations#array-of-ids

**Comment by NomisGnos** [comment]
So the first problem I am seeing is how do I setup with this:

I am using filament's repeater with this. It's storing the IDs as strings. Thus why they are not integers.

Then the recommended way to save the repeater's data is to cast those fields as "arrays".  

Finally, what is the suggestion for a single dimensional array like this?  I assume the example:

`return $this->belongsToJson(Role::class, 'options->roles[]->role_id');`

would be in my case:
`$table->json('units')->nullable();` (from migration)

cast as units => array (from models)

`return $this->belongsToJson(Unit::class, 'units');`

If that's the case, it doesn't seem to work. This could be because the IDs are stored as "strings"...if that is the case, is there around that?

**Comment by staudenmeir** [comment]
> return $this->belongsToJson(Unit::class, 'units');

This line is correct. How did you name the relationship? It shouldn't have the same name as the column (i.e. `units`), that causes all kinds of issues.

> the biggest thing for me is the property from json. There is none in my case.

Do you mean the cast? `array` and `json` are the same.

> This could be because the IDs are stored as "strings"...if that is the case, is there around that?

Some features of the relationship still work with strings but generally, there's no simple workaround. You need to find a way to take the strings from filemant and convert them to integers before storing them. You can try defining a [custom accessor](https://laravel.com/docs/10.x/eloquent-mutators#defining-a-mutator).

**Comment by NomisGnos** [comment]
I renamed the field to not be the same as the model name.  Not sure if that fixed it or not but that seemed to work.  Also, I don't have to typecast the array values. because it returned the correct values.  Thank you for all the good work and help.
