### ISSUE TITLE
MySQL MEMBER OF () performance improvements

### ISSUE THREAD

**Issue by royduin** [staudenmeir/eloquent-json-relations#94]
Just a tip / feature idea; implement [`MEMBER OF()`](https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html#operator_member-of) for MySQL 8.0.17+ which is [a lot faster](https://stackoverflow.com/questions/59538181/why-is-member-of-faster-than-json-contains). Also adding [multi valued indexes](https://dev.mysql.com/doc/refman/8.0/en/create-index.html#create-index-multi-valued) could improve performance further. Those also work with `JSON_CONTAINS()`. Maybe something for in the readme.

**Comment by staudenmeir** [comment]
Thanks, I'll look into it.

**Comment by staudenmeir** [comment]
Have you already tried multi-valued indexes with the package? I started testing them and saw that MySQL doesn't actually use them at the moment due to the SQL generated by Laravel. I'm checking how this can be fixed.

**Comment by royduin** [comment]
I experienced some issues with MySQL 8.0.27 with multi valued indexes not returning any results at all (see: https://github.com/TablePlus/DBngin/issues/103). After upgrading to the latest version 8.0.33 everything works fine.

But, I'm not using this package. I created a "HasManyJson" relation in a project before this package existed but when I came across "member of" I searched for a package with support for that. Saw your package was popular so I created this issue.

But even without the indexes is a lot faster.

I'm using this in a project:
```php
class HasManyJson extends HasOneOrMany
{
    public function addConstraints(): void
    {
        if (static::$constraints) {
            $this->query->whereRaw($this->getParentKey().' MEMBER OF ('.$this->foreignKey.')');

            $this->query->whereNotNull($this->foreignKey);
        }
    }

    public function addEagerConstraints(array $models): void
    {
        $keys = $this->getKeys($models, $this->localKey);

        foreach ($keys as $key) {
            $this->query->orWhereRaw($key.' MEMBER OF ('.$this->foreignKey.')');
        }
    }

    public function getRelationExistenceQuery(Builder $query, Builder $parentQuery, $columns = ['*']): Builder
    {
        return $query->select($columns)->whereRaw(
            $this->getQualifiedParentKeyName().' MEMBER OF ('.$this->getExistenceCompareKey().')'
        );
    }
    ...
```

**Comment by staudenmeir** [comment]
I released a new version that uses `MEMBER OF()` if possible and documented multi-valued indexes. Thanks for the tip!

**Comment by royduin** [comment]
Awesome! 🚀
