### ISSUE TITLE
Is it possible to define a relationship using a key that can be nested at variable depths?

### ISSUE THREAD

**Issue by moham96** [staudenmeir/eloquent-json-relations#95]
Hi,
let's say i have a model "Post" which has a json column that stores a[ tiptap editor output](https://tiptap.dev) which can be nested as deeply as needed, an example of this json is below:
```json
{
  "type": "doc",
  "content": [
    {
      "type": "paragraph",
      "content": [
        {
          "type": "mention",
          "attrs": {
            "id": 6,
            "label": "Jarret Stroman"
          }
        },
        {
          "type": "text",
          "text": " "
        }
      ]
    },
    {
      "type": "bulletList",
      "content": [
        {
          "type": "listItem",
          "attrs": {
            "color": null
          },
          "content": [
            {
              "type": "paragraph",
              "content": [
                {
                  "type": "mention",
                  "attrs": {
                    "id": 5,
                    "label": "Mr. Arthur Wolff III"
                  }
                },
                {
                  "type": "text",
                  "text": " "
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "type": "orderedList",
      "attrs": {
        "start": 1
      },
      "content": [
        {
          "type": "listItem",
          "attrs": {
            "color": null
          },
          "content": [
            {
              "type": "paragraph",
              "content": [
                {
                  "type": "mention",
                  "attrs": {
                    "id": 4,
                    "label": "Stephon Leuschke"
                  }
                },
                {
                  "type": "text",
                  "text": " "
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}
```

each object that has a ```"type":"mention"``` refers to another model (Let's call it `Person`)
Can I form a many to many relationship using the mention nodes?

In other words I don't a have a direct access to the `id` key in the json, instead the PHP/mysql logic that I need should traverse the json and each time it find an object that has ```type:"mention"``` it should look for a neighbouring `attrs` property and then inside should find an `id` property with the number that should be used as an index.

This is probably not possible but I had to ask.

awesome package by the way.

**Comment by staudenmeir** [comment]
Hi @moham96,
Interesting question! What result would you like to get in this case? A collection of all the people that appear anywhere in the JSON object? And the result should be flat, i.e. not nested?

**Comment by moham96** [comment]
> Hi @moham96, Interesting question! What result would you like to get in this case? A collection of all the people that appear anywhere in the JSON object? And the result should be flat, i.e. not nested?

Yes exactly that,
A `Post` can have many `Person`s mentioned

A `Person` can have many `Post`s where they where mentioned

**Comment by staudenmeir** [comment]
Do you need to query both directions, i.e. get all `Person`s of a `Post` and also get all `Post`s that mention a `Person`? Or just the first one?

Do you need eager loading or `has()`/`whereHas()` constraints?

**Comment by staudenmeir** [comment]
Are you using MySQL or MariaDB? Which version?

**Comment by moham96** [comment]
> Do you need to query both directions, i.e. get all `Person`s of a `Post` and also get all `Post`s that mention a `Person`? Or just the first one?
> 
> Do you need eager loading or `has()`/`whereHas()` constraints?

I mainly need to get all `Post`s  that mention a `Person` so the second one.
eager loading would be nice although not mandatory, I don't care for `has()`/`whereHas()`

Regards

**Comment by moham96** [comment]
> Are you using MySQL or MariaDB? Which version?

MySQL version 8.0.33-0ubuntu0.20.04.2

**Comment by moham96** [comment]
Note that i currently have a working solution without using this package which is the following:

I have a pivot table `post_teacher_table` (Teacher=Person in me previous comments):

```php
        Schema::create('post_teacher', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('post_id');
            $table->unsignedBigInteger('teacher_id');
            $table->foreign('post_id')->references('id')->on('posts')->cascadeOnDelete();
            $table->foreign('teacher_id')->references('id')->on('teachers')->cascadeOnDelete();
            $table->unique(['post_id', 'teacher_id']);
            $table->timestamps();
        });

```

then I defined a many to many relationship in both `Post.php` and `Teacher.php`

`Post.php`

```php
public function teachers():BelongsToMany
{
     return $this->belongsToMany(Teacher::class,'post_teacher');
}

```

`Post.php`
```php
public function posts():BelongsToMany
{
    return $this->belongsToMany(Post::class);
}

```

Then all I have to do is each time a `Post` is created or updated I should update the pivot table accordingly which I'm doing by registering an event listener in the `Post` model:

`Post.php`

```php
    protected static function boot()
    {
        parent::boot();
        self::created(fn(Post $post)=>self::attachTeachers($post));
        self::updated(fn(Post $post)=>self::attachTeachers($post));
        
    }

```
which `attachTeachers` is a function that takes a post and will traverse `$post->body` (`body` being the json object) and will search for any node that has `type:'mention'` and then sync the teachers relationship


My current solution works fine, but I was wondering if I could achieve the same thing directly on json, and also which solution would provide the better performance.

Regards

**Comment by staudenmeir** [comment]
> My current solution works fine, but I was wondering if I could achieve the same thing directly on json, and also which solution would provide the better performance.

I did some testing and it looks like it would possible, but I don't think it can be faster than your current solution. The only exception would be that your application is extremely write-heavy and it would be worth replacing the additional sync queries with slower `SELECT` queries.

> find an object that has type:"mention" it should look for a neighbouring attrs property and then inside should find an id property with the number that should be used as an index.

Can the `id` property also appear in a different context or only as part of mentions? In the former case, you could at least speed up JSON queries with an index. In the latter case, a solution with JSON queries would definitely be slower than your current one (at least I don't know a way to use an index).

**Comment by moham96** [comment]
> Can the `id` property also appear in a different context or only as part of mentions? In the former case, you could at least speed up JSON queries with an index. In the latter case, a solution with JSON queries would definitely be slower than your current one (at least I don't know a way to use an index).

Unfortunately a node can has any attrs and so an `id` attr can appear in any node not only mention nodes, so the only way to be 100% sure is to check the `type` property of the node

**Comment by staudenmeir** [comment]
Here's a query that you can use for performance testing:

```php
DB::select(
<<<SQL
select *
from `posts`
where json_contains(
  json_extract(`body`, '$**."content"'),
  '{"type": "mention", "attrs": {"id": 4}}'
)
SQL
);
```

How does it compare to the query that `Teacher::find(4)->posts` executes?

**Comment by moham96** [comment]
> Here's a query that you can use for performance testing:
> 
> ```
> DB::select(
> <<<SQL
> select *
> from `posts`
> where json_contains(
>   json_extract(`body`, '$**."content"'),
>   '{"type": "mention", "attrs": {"id": 4}}'
> )
> SQL
> );
> ```
> 
> How does it compare to the query that `Teacher::find(4)->posts` executes?

Well it seems like the json query is much slower

Tested using laravel `ddd()` I get:
for the `$teacher->posts`: 2.78ms
for the json query: 130.36ms

**Comment by staudenmeir** [comment]
Yeah, the second query benefits massively from using indexes.

Out of curiosity: How much faster is a JSON query that just searches for any `ìd` property, uses the more efficient `MEMBER OF()` and can benefit from an index?

```php
DB::statement(
<<<SQL
ALTER TABLE `posts` ADD INDEX `ids` ((CAST(`body`->'$**."content"[*]."attrs"."id"' AS UNSIGNED ARRAY)));
SQL
);

DB::select(
<<<SQL
select *
from `posts`
where 4 member of(
  json_extract(`body`, '$**."content"[*]."attrs"."id"')
)
SQL
);
```

**Comment by moham96** [comment]
Ok so initially i did the tests using mariadb and not MySQL server (my dev machine had mariadb and my production had MySQL)
I redid the tests by removing mariadb and installing MySQL and I saw improvements in the speed,

- $teacher->posts:  5.23ms
-  json query without index: 33.67ms
-  json query with index: 5.51ms

**Comment by staudenmeir** [comment]
Great, that looks more promising. I assume the editor doesn't have setting to rename the `id` property _just_ for mentions (so you can target it in the queries)?

A hacky workaround would be to rename the `id` property for mentions before saving the JSON content to the database and then reverting this change after reading from the database (using a [mutator](https://laravel.com/docs/10.x/eloquent-mutators)).
