### ISSUE TITLE
Many To Many Eager Loading Breaks with array_key_exists(): Argument #2 ($array) must be of type array, null given

### ISSUE THREAD

**Issue by madsem** [staudenmeir/eloquent-json-relations#99]
Hey there,

when I use this with an array of objects, the relationship breaks when using eager loading, with this exception:
`array_key_exists(): Argument #2 ($array) must be of type array, null given`

Here are my relationships:
```php
# LanderPath
 /**
     * Get the Landers for this LanderPath
     */
    public function landers(): BelongsToJson
    {
        return $this->belongsToJson(Lander::class, 'landers[]->lander_id');
    }


# Lander
/**
     * Get the LanderPaths for this Lander
     */
    public function landerPaths(): HasManyJson
    {
        return $this->hasManyJson(LanderPath::class, 'landers[]->lander_id');
    }
```

```json
# `lander_paths` .`landers`
[{"is_active": false, "lander_id": 18}, {"is_active": true, "lander_id": 19}, {"is_active": false, "lander_id": 20}]
```

Eager Loading Query:
`LanderPath::active()->with('landers')->get()`

When I remove the `[]` from the relationship (ie: `landers->lander_id`), the exception goes away and I get a collection of `LanderPath` models with relationships.

But the other relationship queries stop working like for example relationship counts:
```php
# filamentphp count relation
TextColumn::make('lander_paths_count')
                ->counts('landerPaths')
                ->label('# of Lander Paths')
                ->url(fn (Model $record) => route('lander-paths', ['tableFilters' => ['landers' => ['value' => $record->id]]])),
```

This shows `1` before I remove the `[]`, and `0` after I removed the brackets.

Am I doing something wrong, or is there a bug?

**Comment by staudenmeir** [comment]
Hi @madsem,
The issue seems to be that the JSON column and the relationship are both called `landers` and conflict with each other. Please rename one of them.

**Comment by madsem** [comment]
> Hi @madsem,
> The issue seems to be that the JSON column and the relationship are both called `landers` and conflict with each other. Please rename one of them.

Hey thanks for your reply.

Actually, that's probably not it... Before I posted the name of the column was landing_pages, I renamed it before posting and the results were the same...

**Comment by staudenmeir** [comment]
Did you define a JSON cast in `LanderPath` for this column?

**Comment by madsem** [comment]
Yup, like I said, the relationship works... Only not with eager loading as shown in first post.

**Comment by madsem** [comment]
Ok found the issue, it was the custom json cast I made that casts numeric values to integers... :D Sorry for the trouble!
